- node/src/chain_spec.rs
- test/suites/para/test_tanssi_containers.ts
- test/util/keys.ts
Follow-up to #103, we only want to change the dev_tanssi enviroment (manual seal), not the zombie_tanssi environment.
And add a test to ensure the assignment doesn't change.
And reorder tests.
> Set max_orchestrator_collators=5 in zombienet tests and add tests for that

- .github/workflows/release.yml
- Cargo.lock
- container-chains/templates/frontier/node/Cargo.toml
- container-chains/templates/frontier/runtime/Cargo.toml
- container-chains/templates/simple/runtime/Cargo.toml
- node/Cargo.toml
- runtime/test/Cargo.toml
Adds a check in the CI to make sure runtime-benchmarks compile
> Add runtime benchmarks CI check

- Cargo.lock
- Cargo.toml
Points at custom branches for all repos and cherry-picks the stable compilation changes for all of them
We were also importing two different cumulus repos before, which now should be fixed
> Point custom branches with stable compilation

- .github/workflows/cancel.yml
- .github/workflows/release.yml
Allows to cancel previously running job if new commit is pushed
> Cancel CI job

- client/consensus/src/consensus_orchestrator.rs
Adds force-authoring logic.
TODO: test
> Add force authoring logic

- test/suites/para/test_tanssi_containers.ts
This should fix some of the spurious CI failures.
> Fix test countUniqueBlockAuthors

- container-chains/pallets/authorities-noting/src/mock_proof.rs
- container-chains/pallets/authorities-noting/src/test.rs
- container-chains/templates/simple/runtime/src/lib.rs
- pallets/author-noting/src/test.rs
> Fix some clippy warnings

- .dockerignore
- .github/workflows/release.yml
- docker/container-chain-evm-template.Dockerfile
- docker/container-chain-simple-template.Dockerfile
- docker/tanssi.Dockerfile
- node/src/command.rs
Sets a job in the build process to push images of` tanssi-node` and the container-chain-template nodes to the dockerhub repository
> start working on dockerizing

- node/src/chain_spec.rs
changes the token name for dancebox from UNIT to DANCE
> change unit for dance

- pallets/author-noting/src/mock.rs
- pallets/author-noting/src/test.rs
Increments author-noting test suite by adding some error-test
> increment author noting tests

- test/package.json
- test/pnpm-lock.yaml
- test/suites/smoke-test/test-authority-consistency-assignation.ts
- test/suites/smoke-test/test-block-author-logs.ts
- test/suites/smoke-test/test-configuration-consistency.ts
> add more smoke tests

- test/package.json
- test/pnpm-lock.yaml
Upgrades moonwal to 4.0.5 in util and 4.0.6 in cli
> update MOonwall 4.0.5

- container-chains/templates/frontier/runtime/src/lib.rs
- container-chains/templates/simple/runtime/src/lib.rs
set version 100 for containres (same as tanssi).
Once released we will need to increment again the versions
> set correct version templates

- pallets/registrar/Cargo.toml
- pallets/registrar/src/benchmarks.rs
- pallets/registrar/src/lib.rs
- pallets/registrar/src/tests.rs
Allows the container chain registrar to set boot nodes for the chain as well as root.
> Allows the container chain registrar to set boot nodes for the chain (#178)

- test/moonwall.config.json
Fix stagenet rpc smoke test url
> fix smoketest rpc

- .github/workflows/upgrade-typescript-api.yml
Fixes how to upgrade the version of the typescript api job
> Girazoki fix upgrade tanssi api

- test/suites/smoke-test/test-staking-session-keys.ts
New smoke test testing all candidates have nmbs session keys, because they should not become candidates if they dont
> test all candidates have session keys

- test/configs/dancebox.yml
- test/moonwall.config.json
CHanges wss://fraa-dancebox-rpc.a.dancebox.tanssi.network for wss://dancebox.tanssi-api.network
> Change rpc endpoint

- container-chains/templates/frontier/runtime/src/lib.rs
- test/suites/dev-frontier-template/test-evm/test-evm-rpc-block-author.ts
- test/suites/dev-frontier-template/test-evm/test-evm-transfer-origints.ts
Sets a `FindAuthor` mapping to the Frontier container chain template's EVM config that gets the block author from `AuthorInherent`
Addresses #274
> Set EVM FindAuthor config for Frontier template

- Cargo.lock
- Cargo.toml
Fixes some annoying warnings every time you run a cargo command
> Remove unused jsonrpsee patches

- test/suites/para/test_tanssi_containers.ts
- test/suites/rotation-para/test_rotation.ts
For tests that pass locally, but sometimes fail in CI
> Increase zombienet timeout

- test/suites/smoke-test/test-inflation-rewards.ts
Fixes smoke test related to parachain bond reward
> fix parachain bond smoke test cal

- test/configs/zombieTanssiRotation.json
- test/moonwall.config.json
It doesn't matter because both files have the same contents
> Fix typo in zombienet config

- scripts/build-runtime-srtool.sh
- tools/benchmarking.sh
We will generate weights with production profile from now on
> profile production when building runtime

- pallets/pooled-staking/src/benchmarking.rs
- tools/benchmarking.sh
> fix benchmarking claim manual rewards

- test/suites/dev-tanssi/session-keys/test_remove_session_key.ts
- test/suites/dev-tanssi/session-keys/test_remove_session_key_invulnerables.ts
- test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
Adds test to make sure accounts do not stay even if they remove keys
> Remove session key tests

- Cargo.lock
- pallets/author-noting/src/lib.rs
- test/suites/dev-frontier-template/weights/test_set_latest_authorities_data.ts
- test/suites/dev-tanssi/weights/test_set_latest_author_data_weight.ts
- typescript-api/src/dancebox/interfaces/augment-api-query.ts
Sets weight annotation for `pallet_author_noting::set_latest_author_data` and TS tests for both it and `pallet_authorities_noting.set_latest_authorities_data` weights.
Depends on https://github.com/moondance-labs/dancekit/pull/3
> Set latest authorities data weight annotation & tests

- test/suites/smoke-test/test-randomness-consistency.ts
> Fix smoke test again

- .github/workflows/publish-runtime.yml
- tools/github/generate-runtimes-body.ts
Adds the flashbox runtime to the release process
> release flashbox job

- runtime/flashbox/src/lib.rs
- runtime/flashbox/src/migrations.rs
Add migrations to Flashbox, needed to update the current live network based on dancebox 300
> Flashbox migrations

- pnpm-lock.yaml
- test/package.json
- test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
- test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
> upgrade moonwall to 5.0.0

- pallets/configuration/src/lib.rs
- pallets/configuration/src/tests.rs
Verifies that min_orchestrator_collators < max_collators
> checks on min_orchestrator_collators

- test/scripts/modify-plain-specs.ts
MOdifies the script that injects invulnerables according to latest node release
> new node published now we just use a different way of modifying invul

- runtime/flashbox/src/lib.rs
Changes the value of pallet-balances `MaxFreezes` constant from `0` to `10`.
> Increase `MaxFreezes` to 10

- pallets/pooled-staking/src/candidate.rs
Removes expect/expect err in Pooled Staking pallet in favor of errors.
> Avoid expect/expect_err in Pooled Staking pallet

- test/suites/smoke-test-common/test-collator-number-consistency.ts
- test/suites/smoke-test-common/test-configuration-consistency.ts
- test/suites/smoke-test-common/test-consistency-services-payment.ts
- test/util/payment.ts
One of our smoke tests did not take into account whether chains had enough credits to make sure it has collators assigned. This PR fixes it by creating a common function to check whether we have enough credits
> Fix smoke-tests with respect to collator assignment

- Cargo.lock
- runtime/dancebox/src/lib.rs
- runtime/dancebox/tests/integration_test.rs
- test/suites/dev-tanssi/proxy/test-session-keys-management.ts
- typescript-api/src/dancebox/interfaces/augment-api-tx.ts
- typescript-api/src/dancebox/interfaces/lookup.ts
- typescript-api/src/dancebox/interfaces/types-lookup.ts
This PR allows the delegating of key management
It adds:
- New proxy type 'SessionKeyManagement' in Dancebox runtime
- It adds unit testing for this new type
> MD364 - Adds session key management proxy type

- Cargo.lock
- Cargo.toml
- container-chains/templates/frontier/runtime/Cargo.toml
- container-chains/templates/frontier/runtime/src/lib.rs
- container-chains/templates/simple/runtime/Cargo.toml
- container-chains/templates/simple/runtime/src/lib.rs
- node/Cargo.toml
- node/src/service.rs
- runtime/dancebox/Cargo.toml
- runtime/dancebox/src/lib.rs
- runtime/flashbox/Cargo.toml
- runtime/flashbox/src/lib.rs
Technically only container chains need this, but if we don't implement it for tanssi then the code does not compile, because we assume that the ContainerChainClient has the same set of RuntimeApi as the tanssi Client
> Implement custom slot duration runtime api for runtimes

- Cargo.lock
- client/consensus/src/collators/basic.rs
- container-chains/templates/frontier/node/Cargo.toml
- container-chains/templates/simple/node/Cargo.toml
- node/Cargo.toml
Backport of https://github.com/moondance-labs/tanssi/pull/472
> make basic collator aware of last included block [Backport to 0.5.2]

- client/consensus/src/collators/basic.rs
Up to now the basic collator was not aware of whether the `parent_block` was the las one included in the relay, which could cause the client to try to produce a block and fail. This new function checks whether the `parent_block_hash` is the same one as the last block included in the relay for this parachain
> make basic collator aware of last included block

- test/suites/smoke-test-common/test-configuration-consistency.ts
- test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
- test/suites/smoke-test-dancebox/test-staking-consistency.ts
This PR fixes flashbox and dancebox  smoke test failures.
> Fix flashbox and dancebox smoke test

- Cargo.lock
- Cargo.toml
- client/consensus/Cargo.toml
- client/consensus/src/collators/lookahead.rs
- node/Cargo.toml
- node/src/container_chain_spawner.rs
- node/src/service.rs
This PR changes `call_collate_on` to use cancellation token and exit notification to stop it gracefully as well as wait for it to exit.
> Use cancellation token and exit notifications instead of watch

- test/suites/smoke-test-dancebox/test-staking-consistency.ts
This PR fixes the staking inconsistency test namely `S05C01` by preventing division by zero.
> Fix division by zero in staking inconsistency test

- runtime/dancebox/tests/common/mod.rs
- runtime/dancebox/tests/integration_test.rs
- runtime/flashbox/tests/common/mod.rs
- runtime/flashbox/tests/integration_test.rs
By default set ALICE and BOB as collators and give them some initial balance.
> Implement Default for ExtBuilder and simplify integration tests

- Cargo.lock
- runtime/flashbox/Cargo.toml
- runtime/flashbox/src/lib.rs
Adds can_build_upon rt-api in flashbox
> build_upon implementation in flashbox

- runtime/flashbox/src/lib.rs
> increase maxLenghtParas for flashbox

- .github/workflows/publish-runtime-chevdor.yml
- .github/workflows/publish-runtime.yml
- client/consensus/src/tests.rs
Add possibility to release only flashbox or only dancebox
> add new runtime publishing possibilities

- Cargo.lock
- container-chains/runtime-templates/frontier/src/lib.rs
- container-chains/runtime-templates/simple/src/lib.rs
- runtime/dancebox/src/lib.rs
It removes boiler plate  by using the benchmarking code set for these cases in pallet-foreign-asset-creator
> use the benchmarking code for foreign-assets

- test/configs/zombieTanssiParathreads.json
- test/configs/zombieTanssiRotation.json
- test/configs/zombieTanssiWarpSync.json
Reduces the validators required in the zombienet tests to their minimum
> reduce validators in zombienet tests to minimum

- runtime/flashbox/src/lib.rs
To adapt to the capacity we have
> increase collator num for flashbox

- test/suites/smoke-test-common/test-inflation-rewards.ts
Fixing a lint error left by PR: https://github.com/moondance-labs/tanssi/pull/541
> Fixing lint error

- test/README.md
Expand the chopsticks section of the readme with info that would have helped me.
> Docs: polish chopsticks docs

- node/src/container_chain_spawner.rs
We still leave one folder, "network", because it has a p2p key inside: "secret_ed25519".
> Remove empty folders after removing container db folder

- runtime/common/src/migrations.rs
> add weight to migrations for registrar

- test/suites/smoke-test-common/test-configuration-consistency.ts
- test/suites/smoke-test-common/test-consistency-services-payment.ts
Tested against `smoke-test-failure-85 `
> fix, hopefully for all, tests regarding consistency payment

- scripts/bump-runtime-versions.sh
Usage:
```
./scripts/bump-runtime-versions.sh --client-version=0.9.0 --runtime-version=900
```
> Add script to automatically bump all runtimes and clients to a new version

- Cargo.lock
- solo-chains/runtime/starlight/Cargo.toml
- solo-chains/runtime/starlight/src/lib.rs
Add `pallet_initializer` to `starlight` runtime
> Add `pallet_initializer` to `starlight` runtime

- Cargo.lock
- solo-chains/runtime/starlight/Cargo.toml
- solo-chains/runtime/starlight/src/genesis_config_presets.rs
- solo-chains/runtime/starlight/src/lib.rs
- solo-chains/runtime/starlight/tests/common/mod.rs
- solo-chains/runtime/starlight/tests/integration_test.rs
Adds Tanssi's pallet_configuration to Starlight runtime as `CollatorConfiguration`.
Also set's up basic integration tests for the runtime
> Starlight CollatorConfiguration pallet and basic integration tests

- solo-chains/runtime/starlight/src/lib.rs
Removes pallets related to slot and auctions as we are going to use the `coretimeAssignmentProvider` for this. In general we will dictate through `coretimeAssignemntProvider` how the different containers will be assigned to cores, probably dictated by our assignment algorithm (if you have collators assigned, we schedule a core for you).
In this regard I believe the following pallets are non-needed:
**slots**: which was used to calculate when an auction-based slot was ending.
**Auctions**: which was used to start new auctions that parachains could win
**Crowdloan**: which was used to finance parachains seeking for an auction slot
**AssignerSlots**: which was used to mgirate existing leases to the coretime chain
> Remove slot-related non-needed pallets in starlight

- runtime/dancebox/tests/common/xcm/core_buyer_common.rs
Fix broken master with the merge of https://github.com/moondance-labs/tanssi/pull/599
> fix master

- solo-chains/client/cli/src/command.rs
- test/configs/zombieStarlight.json
- test/moonwall.config.json
Adds one parachain to produce blocks with appropriate collators (at least until we can assign then from tanssi)
Detected an error based of the order of the workers
> Test relay parachain

- Cargo.lock
https://github.com/moondance-labs/polkadot-sdk/commit/be526b072ff5a6894fd49c9f87c5650881bc594f
> Update polkadot-sdk to revert debug log

- solo-chains/runtime/starlight/src/lib.rs
Remove should_end_session check in Starlight because it always returns false
> Remove should_end_session check in Starlight, it always returns false

- Cargo.toml
- solo-chains/client/cli/Cargo.toml
- solo-chains/node/tanssi-relay-service/Cargo.toml
In master this doesn't compile because of missing std features:
```
cargo build --release -p tanssi-relay
```
This PR fixes that.
> Add missing std features to fix build with -p tanssi-relay

- .github/workflows/prepare-tanssi-relay-binary.yml
- .github/workflows/publish-docker-tannsi-relay.yml
- docker/starlight.Dockerfile
Added Dockerfile configuration for Starlight
> CI: Adding Starlight to Docker

- scripts/build-runtime-srtool.sh
- tools/github/generate-runtimes-body.ts
Fixes runtime release job for starlight
> Fix runtime release

- .github/scripts/coverage-report.py
just changes the visualization on the coverage job
> more visual symbols for ups and downs

- runtime/flashbox/src/lib.rs
- scripts/bump-runtime-versions.sh
And fix flashbox outdated spec version
> Add starlight support to version bump script

- .github/workflow-templates/typescript-tests-moonwall/action.yml
- .github/workflow-templates/zombienet-tests/action.yml
- .github/workflows/client-release-issue.yml
- .github/workflows/publish-binary-tannsi-relay.yml
- .github/workflows/publish-binary.yml
- .github/workflows/publish-runtime-chevdor.yml
- .github/workflows/publish-runtime.yml
- .github/workflows/publish-typescript-api.yml
- .github/workflows/release.yml
- .github/workflows/run-zombienet-tests.yml
- .github/workflows/runtime-release-issue.yml
- .github/workflows/upgrade-typescript-api.yml
- .github/workflows/version-bump.yml
Upgrades the node version to 22
> use node version 22 in all our jobs

- .github/workflows/publish-binary-tannsi-relay.yml
Add workers to upload files github script which we missed
> publish fix for workers

- test/configs/zombieDancelightUnneededPara.json
- test/moonwall.config.json
- test/suites/zombie-tanssi-relay-unneeded-para/test-tanssi-relay-unneeded-para.ts
Does not run in CI because it fails.
To reproduce this bug we need a collator that:
* Creates block for a para
* That para runs out of credits
* Validator keeps banning that collator
> Add zombienet suite for unneeded para bug

- solo-chains/runtime/dancelight/src/bridge_to_ethereum_config.rs
Updates holesky params as they were wrong.
We need to cherry-pick this into runtime-1000
> change ethereum params

- pnpm-lock.yaml
- typescript-api/package.json
- Updated PolkadotJS to v15 
- Updated other dependencies
> update polkadot api and other dependencies in typescript-api

- .github/workflow-templates/bridge-e2e/action.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-test-bridge.yml
- .github/workflows/release.yml
Introduces merge queue changes such that certain tests only run in merge queues. These are the following:
- zombienet bridge e2e
- zombienet rotation
- zombienet data preservers
> introduce merge queue changes

- .github/workflows/prepare-binary.yml
- .github/workflows/prepare-tanssi-relay-binary.yml
- .github/workflows/publish-binary-tannsi-relay.yml
installs protoc in all tanssi-release jobs
> install always protoc in tanssi-release

- .github/dependabot.yml
It was using all of our CI machines
> Disable automatic rebase in dependabot.yml

- Cargo.lock
- chains/container-chains/nodes/frontier/Cargo.toml
- chains/container-chains/nodes/simple/Cargo.toml
- chains/container-chains/runtime-templates/frontier/src/lib.rs
- chains/container-chains/runtime-templates/simple/src/lib.rs
- chains/orchestrator-paras/node/Cargo.toml
- chains/orchestrator-paras/runtime/dancebox/src/lib.rs
- chains/orchestrator-paras/runtime/flashbox/src/lib.rs
- chains/orchestrator-relays/node/tanssi-relay-service/Cargo.toml
- chains/orchestrator-relays/node/tanssi-relay/Cargo.toml
- chains/orchestrator-relays/runtime/dancelight/src/lib.rs
Increased node and runtime versions
> Bump node and runtime versions to 0.12.0 and 1200

- .github/workflows/release.yml
Reverts back a change that prevented docker builds to happen
> fix docker comp

- test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
- Skip the SMOK05->C03 if the chain is fresh
> In case of fresh chain, we don't have enough history to check the RewardPointsForEra

- chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
Replaces holesky with Sepolia, given that holesky will take still some time to resolve we move to sepolia
> Add sepolia

- test/scripts/bridge/deploy-ethereum-contracts.sh
- test/scripts/bridge/set-env.sh
- test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
This PR updates tanssi symbiotic repo commit and e2e test to work with middleware v2.
> Use middleware v2 in e2e test

- test/scripts/bridge/set-env.sh
- test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts
This PR upgrades e2e test to use latest commit in tanssi-symbiotic repository. And also makes changes in e2e test so that it can work with latest middleware.
> Update e2e test to be compatible with latest middleware version

- docker/container-chain-evm-template.Dockerfile
- docker/container-chain-simple-template.Dockerfile
- docker/starlight.Dockerfile
- docker/tanssi.Dockerfile
Fix Dockerfile labels to prevent GH actions warnings on every PR
> Fix Dockerfile maintainer label

- .github/workflows/cmd.yml
- .github/workflows/release.yml
- typescript-api/src/dancebox/interfaces/registry.ts
**Description:**
- This PR fix the CI job that can be triggered from the PR comment.
**What's done:**
- Updated the checkout command
- Added rebase in case if any new commit appeared after job started
> Test TS api generate command

- .github/workflows/publish-runtime.yml
- tools/github/print-runtime-release-issue.ts
Updates release instructiosn for runtimes
> update release instructions for runtimes

- .github/workflows/client-release-issue.yml
- tools/github/print-client-release-issue.ts
This PR improves node release template by separating out the issue guide in two tracks:
1. Parachain: For parachain and templates
2. Solochain: For solochain
It also changes the issue title to reflect whether the issue is for parachain or solochain as well.
> Improve node release template

- .github/workflows/release.yml
- test/configs/zombie_dancebox_upgrade.json
- test/moonwall.config.json
- test/scripts/build-spec-dancebox.sh
- test/suites/smoke-test-dancelight/test-external-validators-rewards.ts
**Description:**
This PR improves a way to run zombie_dancebox_upgrade locally by re-using the same scripts we have for other zombie* tests.
> [MD-883] Simplify running `zombie_dancebox_upgrade` locally

- .github/workflow-templates/cargo-build/action.yml
- .github/workflows/publish-runtime.yml
**Description:**
This PR adds the starlight runtime summary to the publish job + artifacts
> Updated  release job to publish starlight runtime artifacts for the release

- pallets/registrar/src/lib.rs
Fixes a left unsafe math in palelt registrar
> unsafe math leftover in pallet registrar

- Cargo.lock
- typescript-api/src/dancebox/interfaces/lookup.ts
- typescript-api/src/dancebox/interfaces/types-lookup.ts
- typescript-api/src/dancelight/interfaces/lookup.ts
- typescript-api/src/dancelight/interfaces/types-lookup.ts
- typescript-api/src/flashbox/interfaces/lookup.ts
- typescript-api/src/flashbox/interfaces/types-lookup.ts
Points to new commit to get new limits in container chain genesis data
> point to new bounded limits in container chain genesis data

- chains/orchestrator-relays/runtime/starlight/src/lib.rs
- chains/orchestrator-relays/runtime/starlight/src/tests/test_disabled_extrinsics.rs
- test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
Enable reward messages
Enable token transfers over bridge (only for tanssi token)
> Enable bridges pallets

- chains/orchestrator-relays/runtime/starlight/src/lib.rs
- chains/orchestrator-relays/runtime/starlight/src/tests/inflation_rates.rs
Total annual inflation: 7.5%
Split between:
* Validators: 4%
* Collators+bond: 3.5%
Out of the 3.5%:
* 2% to collators
* 1.5% to parachain bond
> Change inflation values for mainnet

- chains/orchestrator-relays/runtime/starlight/src/lib.rs
**Description:**
- Incorporated the [PR](https://github.com/moondance-labs/tanssi/pull/985) for Dancelight missing API-s
> [MD-1109] Missing API-s for starlight

- typescript-api/package.json
- typescript-api/scripts/runtime-upgrade.ts
- typescript-api/src/starlight/index.ts
- typescript-api/src/starlight/interfaces/augment-types.ts
- typescript-api/src/starlight/interfaces/index.ts
- typescript-api/src/starlight/interfaces/lookup.ts
- typescript-api/src/starlight/interfaces/registry.ts
- typescript-api/src/starlight/interfaces/types-lookup.ts
- typescript-api/src/starlight/interfaces/types.ts
- typescript-api/src/starlight/tsconfig.json
- Add typescript API for the Starlight runtime
> [MD-1111] Added typescript API for starlight

- tools/benchmark-all-runtimes.sh
Add missing folder for starlight weights
> Add starlight weights tmp folder

- test/suites/smoke-test-dancelight/test-invulnerables-priority.ts
- test/suites/smoke-test-dancelight/test-randomness-consistency.ts
- test/suites/smoke-test-dancelight/test-staking-consistency.ts
Adds some new smoke tests that were present in dancebox and were not prsent in dancelight.
> add new smoke tests dancelight

- .github/workflows/test-all-benchmarks-schedule.yml
- tools/benchmark-all-runtimes.sh
Removed unneeded files from the commit list
> Benchmarking CI script fix

- Cargo.lock
Point to latest polkadot commit
> point to latest polkadot

- .github/workflows/publish-runtime.yml
Adds dancelight only and starlight only to publish runtime job
> add dancelight only and sarlight only to publish runtime

- .github/workflows/publish-docker.yml
> fix publish docker

- test/suites/smoke-test-common-all/test-fee-treasury.ts
**Description**
This PR fixes the smoke test for the Treasury
> Treasury smoke test fix - filter events by extrinsic index

- test/scripts/bridge/set-env.sh
https://github.com/moondance-labs/tanssi-symbiotic/pull/121
> point to latest potential mastter in tanssi-symb

- chains/container-chains/runtime-templates/frontier/src/migrations.rs
- chains/container-chains/runtime-templates/simple/src/migrations.rs
- chains/orchestrator-paras/runtime/common/src/migrations.rs
> Remove passed migrations

- test/suites/smoke-test-common-all/test-consistency-services-payment.ts
- test/suites/smoke-test-common-all/test-data-preservers.ts
- test/suites/smoke-test-common-parachain/test-configuration-consistency.ts
- test/suites/smoke-test-common-solo/test-configuration-consistency.ts
This PR fixes smoke tests:
- Incorrect check if the container not exist in the authority assignment
- The deposit has changed and now we need to compare agains both values
> Fixes for smoke tests

- SECURITY.md
Adding SECURITY.md file to the root
> Add SECURITY.md via upload

- test/suites/smoke-test-common-solo/test-ethereum-token-transfers.ts
**Description**
Improve the error processing in case if the event payload is unknown
> [MD-1197] Improve smoke ETH token transfer for ethereumInboundQueue

- test/scripts/bridge/set-env.sh
I accidentally merged temporary commits from branches before
> tanssi symbiotic final commits

- test/suites/smoke-test-common-solo/test-era-changes.ts
- test/utils/block.ts
This PR fixes the smoke test for era changes
> Fix for era changes smoke test

- .github/workflow-templates/cargo-build/action.yml
This PR adds RUSTFLAGS as a dependency for cache invalidation.
> Fix build caching for the coverage case

- tools/github/print-runtime-release-issue.ts
- typescript-api/package.json
updates ts api to have the next runtime. 1500 and modify instructions
> update api to 1500

- chains/orchestrator-paras/runtime/dancebox/src/xcm_config.rs
- pallets/services-payment/src/lib.rs
- pallets/xcm-core-buyer/src/lib.rs
Its equivalent but shorter.
If the storage is an `OptionQuery`, `Storage::set` accepts an `Option<Value>`, and removes it if its `None`.
> Use Storage::set instead of if let Some

- test/suites/smoke-test-common-parachain/test-inflation-rewards.ts
- test/suites/smoke-test-common-solo/test-inflation-rewards.ts
- test/utils/constants.ts
**Description:** 
Flashbox smoke fix for inflation rewards
> Flashbox smoke fix for inflation rewards

- typescript-api/package.json
This PR updates the URL for fetching dancebox metadata
> Update URL for Dancebox metadata

- test/chain-log-alerts/README.md
- test/chain-log-alerts/log-rules.json
This PR adds the list of string patterns that will be monitored in the live chains.
> Chains Log Alerting Rules

- .github/workflows/release.yml
- test/configs/frontierContainer.yml
- test/scripts/fetchRuntimeApi.ts
- test/scripts/unhashKey.ts
- test/suites/zombie_tanssi_relay/test_receive_container_native_tokens_from_eth.ts
Simply to stop running chopstikcs against chains that no longer exist
> not run chopsticks upgrade dancebox

- Cargo.lock
Update polkadot sdk commit in Cargo.lock to include chain stall fix: https://github.com/paritytech/polkadot-sdk/pull/9564
> Update polkadot-sdk commit in Cargo.lock to include chain stall fix

- scripts/run-release-workflows.sh
fixes small issues with release script
> small fixes release script

- test/suites/smoke-test-dancebox/test-inactivity-tracking.ts
- test/utils/block.ts
This PR Reverts implementation of `getLastSessionEndBlock` for dancebox runtime
> Reverted implementation of `getLastSessionEndBlock` for dancebox runtime

- .github/workflows/bump-runtime-versions.yml
> Fix bump-runtime-versions.yml

- test/suites/zombie_tanssi_relay/test_zombie_tanssi_relay.ts
- test/utils/block-production-monitor.ts
- test/utils/block.ts
- test/utils/zombie.ts
This PR improves the zombienet tests developer experience. What is added:
- Added block production monitoring for zombienet
- Added stack trace for the error
> [MD-1339] Zombienet tests improvements
