moondance-labs/tanssi

container-chains/templates/frontier/node/src/chain_spec.rs
container-chains/templates/simple/node/src/chain_spec.rs
node/src/chain_spec.rs
pallets/registrar/src/tests.rs
primitives/container-chain-genesis-data/src/json.rs
primitives/container-chain-genesis-data/src/lib.rs
test/suites/para/test_tanssi_containers.ts

Add `isEthereum` field to ChainSpec properties. In the future this will allow polkadot.js and similar apps to detect whether a parachain is using ethereum-style addresses, but for now it does nothing. The default value is `true` for the frontier template, and `false` for the simple template and for the orchestrator chain.

Add isEthereum ChainSpec property

---

test/suites/dev/weights/test_on_session_change_weight.ts

This is on session change:
```
{
normal: { refTime: 0, proofSize: 0 },
operational: { refTime: 0, proofSize: 0 },
mandatory: { refTime: 503740332000, proofSize: 5243886 }
}
```
And this is a normal block:
```
{
normal: { refTime: 0, proofSize: 0 },
operational: { refTime: 0, proofSize: 0 },
mandatory: { refTime: 3740332000, proofSize: 1006 }
}
```
In the tests I only check that the value is greater or smaller than 500_000_000_000, which is the max weight used in pallet session.

Add test for block weight on session change

---

runtime/test/tests/common/mod.rs
runtime/test/tests/integration_test.rs

Fixes the fact that when you do `cargo test --features=fast-runtime` the tests fail. This is because certain author verification (which is slot dependent) happens at even slots numbers with slow sessions and at odd slot numbers with fast sessions. I re-adapted the tests to work regardless of which one we are using

Adapt tests to pass rregardless if they run with fast or slow runtime

---

Cargo.lock

Update some yanked crates, and fix this vuln: https://rustsec.org/advisories/RUSTSEC-2023-0034

Update deps to fix cargo audit warnings

---

test/suites/dev-frontier-template/test-pallet-cc-authorities-noting/test-orchestrator-para-id.ts
test/suites/dev/test-pallet-configuration/test-active-config-collators-per-container.ts
test/suites/dev/test-pallet-configuration/test-active-config-max-collators.ts
test/suites/dev/test-pallet-configuration/test-active-config-max-orchestrator-collators.ts
test/suites/dev/test-pallet-configuration/test-active-config-min-orchestrator-collators.ts
test/suites/dev/test-pallet-configuration/test-active-config-origin.ts

add typescript tests for pallet-configuration and pallet-cc-authorities-noting

[MD-107] Add typescript tests for pallet-configuration and pallet-cc-authorities-noting

---

runtime/dancebox/src/lib.rs

Sets the dancebox version to 0100, where:
- first two digits indicate a major version
- second two digits indicate the minor version

increment dancebox

---

container-chains/templates/simple/runtime/src/lib.rs

harmonize the implementation across both runtimes. We should at some point move this into a primtives crate

harmonize canAuthor between both templates

---

test/suites/para/test_tanssi_containers.ts

This should make the test wait for 1 block less, reducing the time it takes to run all the tests.

Improve test by executing 2 transactions at the same time

---

runtime/dancebox/src/lib.rs

Reduce session lengths in dancebox to 1 hour to make sure changes are reflected in less time

reduce session length in prod

---

.github/workflows/release.yml

Modularizes CI to use most of the steps on git_ref plus allowing to choose a commit on a workflow dispatch against which one can run

Run CI jobs in appropriate context

---

Cargo.lock
Cargo.toml

Using this moonkit branch, which is identical to moonbeam-polkadot-v0.9.43 except the git urls: https://github.com/Moonsong-Labs/moonkit/compare/moonbeam-polkadot-v0.9.43...moondance-labs:moonkit:tanssi-polkadot-v0.9.43

Use moonkit repo instead of nimbus

---

.github/workflows/publish-docker-runtime-containers.yml
.github/workflows/publish-docker-runtime-tanssi.yml
.github/workflows/publish-docker-runtime.yml
.github/workflows/publish-runtime.yml
scripts/build-runtime-srtool.sh
tools/github/generate-runtimes-body.ts
tools/github/print-runtime-release-issue.ts

This pull request allows us to make releases for tanssi runtimes, templates, or both. The CI job now allows you to choose between releasing:
- `tanssi-only`
- `templates-only`
- `run-all`
The PR modifies the CI job such that it is quite easy to add a new template, since it only involves adding a new element to a json, formatted structure in the job prepare_matrix, e.g.:
`dancebox='{"runtime_name": "dancebox","runtime_path" : "./runtime/dancebox/src/lib.rs"}'
`
I also decoupled the draft release preparation into first pushing the release (non-matrixed) and then uploading the files (matrixed)
The scripts have been modified to support releasing both containers and tanssi runtimes too.
An example of a run only for templates can be seen in: …

Allow modularizing releases tanssi-templates

---

Cargo.lock
Cargo.toml
client/consensus/src/lib.rs
node/Cargo.toml
node/src/container_chain_spawner.rs
node/src/service.rs
primitives/consensus/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/integration_test.rs
test/moonwall.config.json
test/suites/para/test_tanssi_containers.ts

This PR allows starting container chains that will start collating in the future, for example in the next session.
The main feature is the `partial_start_collator` function, which starts the collation subsystem for a container chain but doesn't enable it, leaving that to the caller. This works the same way as the `collate_on_tanssi` feature, which has already been implemented before.
Now we start container chains one session in advance, and start collating later when they we are actually assigned. 
Also changed the way `ContainerChainSpawner` works, instead of having `Start` and `Stop` messages, we now only have a `UpdateAssignment` message. This allows the `ContainerChainSpawner` to keep track of which container chains should be running or should be stopped, and which one should be …

Separate spawning container chain and starting collation

---

Cargo.lock
Cargo.toml
node/Cargo.toml
pallets/author-noting/rpc/runtime-api/Cargo.toml
pallets/author-noting/rpc/runtime-api/src/lib.rs
pallets/author-noting/src/benchmarks.rs
pallets/author-noting/src/lib.rs
pallets/author-noting/src/tests.rs
runtime/dancebox/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/integration_test.rs
test/suites/para/test_tanssi_containers.ts

Change type of `pallet_author_noting::LatestAuthor` storage item from `AccountId` to `(BlockNumber, AccountId)`. This is because we want to store the container chain block number along with the author.
Add runtime api that allows to query latest author and latest block number for a container chain.

Change AuthorNoting to include block number, and add runtime api

---

Cargo.lock
container-chains/templates/frontier/runtime/src/lib.rs
container-chains/templates/simple/runtime/src/lib.rs
test/suites/dev-frontier-template/test-eth-block/test-eth-block-pending.ts

Brings https://github.com/paritytech/frontier/pull/1115 and sets the correct value in the max block gas and miliseconds per block, so that gas calculation is correct with respect to weight

Fix ethereum gas pricing

---

.github/workflows/cancel.yml

Currently we only cancel on a new PR the release.yml job, but we should also cancel the coverage one

cancel release and coverage jobs

---

test/suites/warp-sync/test_warp_sync.ts

context.waitBlock was waiting for a new block on the wrong chain, meaning that the container chain could still be at block N when we call getBlock(N+1), resulting in error:
→ Unable to retrieve header and parent from supplied hash

Fix race condition in zombienet test

---

.github/workflows/publish-docker-runtime-containers.yml

Removes tanssi from the job which publishes runtimes for containers

remove tanssi from the containers job

---

.github/workflows/publish-typescript-api.yml
typescript-api/package.json

Without this change the typescript-api was not able to be published

Remove build from typescript publishing

---

pnpm-lock.yaml
test/package.json
test/suites/rt-ugprade-chopsticks/test-upgrade-chain.ts

The chopsticks upgrade tests fail randomly because we use the fast-runtime runtime when we upgrade, which has a session length of 5. If we try to send the tx at the same time at which we have a session change, it fails because session change blocks dont allow any other tx to be submitted.
The test is modified such that we re-try at most 5 times to send the tx, which should fix the behavior seen in the CI

upgrade moonwall and fix chopsticks test

---

runtime/dancebox/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/dancebox/src/migrations.rs
runtime/dancebox/tests/integration_test.rs
typescript-api/src/dancebox/interfaces/augment-api-query.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/registry.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts

Migrates hold identifier from [u8; 8] to a proper enum holdReason

migration for hold identifier

---

test/moonwall.config.json

Before this PR:
`pnpm moonwall test dancebox_smoke`
would run on stagenet dancebox.
Now:
`pnpm moonwall test dancebox_smoke`
Will run on dancebox, and
`pnpm moonwall test stagenet_dancebox_smoke`
will run on stagenet dancebox

Fix dancebox rpc for smoke tests

---

.github/workflow-templates/cargo-build/action.yml
.github/workflows/coverage.yml

The coverage job was not setting the "fast-runtime" feature because the cargo-build template was ignoring that argument.
This is the command that was being run before:
https://github.com/moondance-labs/tanssi/actions/runs/6145058170/job/16671718848
This is now:

Fix workflow template features

---

test/configs/dancebox.yml
test/configs/stagenet-dancebox.yml

Otherwise chopsticks upgrade job fails, because chopsticks is unable to produce blocks when the list of registered para ids is not empty

Mock pending registered para ids for chopsticks

---

Cargo.lock
test/configs/zombieTanssi.json
test/configs/zombieTanssiMetrics.json
test/moonwall.config.json
test/suites/metrics/test_metrics_stop.ts

This is the fix: https://github.com/moondance-labs/substrate/commit/b06f357724147a9bc4d2b5cf831f8ff714d74f37
This PR includes a new zombienet suite just to test that case, but it is not being run in CI.

Fix metrics server not stopping if there are open connections

---

node/src/service.rs
test/suites/para/test_tanssi_containers.ts
test/suites/warp-sync/test_warp_sync.ts

I found a bug while testing #267, if all the tanssi collators rotate at the same time, tanssi chain is stalled because no one produces blocks. This fixes it, by delaying the rotation until the tanssi block is finalized. The old behavior triggered the rotation before sending the block to the relay, so if the session change was in block 25, the chain got stuck at block 23.
Will add tests for this case in #267

Fix collators rotating 1 block too early

---

pallets/configuration/src/lib.rs
pallets/configuration/src/tests.rs

To avoid bricking the chain by accidentally setting num_collators = 0

Add extra consistency checks to pallet_configuration

---

runtime/dancebox/src/lib.rs

Reduce the initial value to have lower rounding errors when distributing rewards.

Reduce initial value of shares

---

test/configs/zombieDanceboxUpgrade.json
test/configs/zombieTanssi.json
test/configs/zombieTanssiMetrics.json
test/configs/zombieTanssiWarpSync.json

Because it logs many errors like:
Got message from unregistered peer
BadJustification("Duplicate consensus engine ID")

Disable beefy in zombienet

---

pallets/initializer/src/lib.rs
pallets/initializer/src/tests.rs
runtime/dancebox/src/lib.rs
typescript-api/src/dancebox/interfaces/augment-api-query.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/registry.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts

Delaying the application of a new session until `on_finalize` was producing unwanted behavior. This changes it to be applied immediately on `apply_new_session`, and removes `BufferedSessionChange` as it was only used to temporarily save the session change until `on_finalize`

pallet-initializer new session is applied immediately 

---

client/consensus/src/lib.rs
client/consensus/src/tests.rs
node/src/service.rs

Fixes panics spotted by @tmpolaczyk on zombie tests due to an invalid prediction that could cause collator to reduce reputation
Before: author prediction was based on where you are assigned with respect to the runtime-api, but not on whether the collation process is already up for such paraId. This caused the node to believe it was eligible, but in reality, it was still proposing in the old assignation.
After: author prediction is based on the para id of the collation process. This provides a smoother prediction in which authors will not try to propose until the collation process is ready for it

rework prediction with the paraId in which you are assigned

---

pallets/collator-assignment/src/lib.rs
pallets/collator-assignment/src/mock.rs
pallets/collator-assignment/src/tests.rs
primitives/traits/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/common/mod.rs
runtime/dancebox/tests/integration_test.rs

When rotating collators, the orchestrator chain will be filled with `min_orchestrator_collators` invulnerables. If there are not enough invulnerables, the rest is filled with regular collators. The rest (up to `max_orchestrator_collators`) is also filled with regular collators (regular means anything, can be invulnerable or not invulnerable).

Give priority to invulnerables as orchestrator collators

---

pallets/configuration/src/lib.rs
pallets/configuration/src/tests.rs

Removes the check inside `pallet-configuration` that prevented setting zero as a value of `full_rotation_period` field within `HostConfiguration`.

Allow to set zero as rotation period in pallet-configuration

---

pallets/pooled-staking/src/mock.rs
pallets/pooled-staking/src/pools.rs
pallets/pooled-staking/src/tests/rewards.rs

Make reward distribution reverts if anything goes wrong.

make distribute_rewards transactional

---

.github/workflows/enforce-pr-labels.yml
.github/workflows/prepare-binary.yml
.github/workflows/publish-runtime.yml
tools/github/generate-release-body.ts
tools/github/github-utils.ts

CI improvementes related to:
- usage of polkadot-sdk repo now
- needing 1.70 rust to build
- creation of label checks

Girazoki ci improvement

---

test/suites/smoke-test/test-inflation-rewards.ts
test/suites/smoke-test/test-randomness-consistency.ts
test/util/block.ts

Smoke tests for inflation rewards, only runs against runtimes >300

add inflation rewards smoke test

---

node/src/container_chain_monitor.rs
node/src/container_chain_spawner.rs

Container chains can start in "sync mode", which uses random ports, or in "collation mode" which uses the ports provided by the user through CLI. To ensure that the container chain that is currently collating uses the correct ports, we restart it right when it is time to start collation.

Always restart container chain before starting collation

---

node/src/chain_spec.rs
test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts

This is needed for the StakingAccount, not sure if the other ones need it as well

Prefund pallet accounts in genesis to ensure they are always alive

---

runtime/dancebox/tests/integration_test.rs

The issue was doing `x * 2 / 10` instead of `Perbill::from_percent(20) * x`.

Fix rounding in inflation test

---

.github/workflows/coverage.yml

Generate covdir files in coverage for new coverage report

generate covidr

---

pallets/author-noting/src/lib.rs
pallets/author-noting/src/tests.rs

When reading the author for a container chain, we currently assume that the first log item will be the aura log. This PR iterates over all the logs, in case container chains have something else aside from aura.

author-noting: check all the digests, not only the first one

---

.github/workflows/coverage.yml

Prevents the creation of junk `.profraw` files in the `~/.cargo` folder. Now coverage is enabled after cargo build, and `.profraw` files are written directly to the `proffiles` folder.

Disable coverage gathering during cargo build

---

node/src/cli.rs
node/src/container_chain_spawner.rs

Fix a panic when bootnodes are invalid. A container chain with zero valid boot nodes will still start, even though it probably won't find any peers and therefore the collator will not produce any blocks.
Can be tested using the `set_boot_nodes` extrinsic in `zombie_tanssi`, test cases:
0xff (invalid utf8)
A (invalid multiaddr)

Ignore invalid bootnodes when starting container chain

---

node/src/container_chain_spawner.rs
test/suites/keep-db/test_restart_keep_db.ts
test/suites/rotation-para/test_rotation.ts
test/suites/warp-sync/test_warp_sync.ts

The current default is rocksdb, but warp sync seems to be broken with rocksdb. So from now on, container chains can only use paritydb. Unblocks #361

Force container chains to use paritydb

---

node/src/container_chain_spawner.rs
test/suites/keep-db/test_restart_keep_db.ts
test/suites/rotation-para/test_rotation.ts
test/suites/warp-sync/test_warp_sync.ts

We were not setting the sync mode properly for container chains, which resulted in them always using full sync.

Fix container chain sync mode being ignored

---

container-chains/templates/frontier/node/src/command.rs
container-chains/templates/simple/node/src/command.rs
test/moonwall.config.json
test/suites/dev-frontier-template/test-balance/test-balance-existential.ts

Prior to this change, the local execution of templates nodes was failing as there was a mismatch with the default `para-id` for the `orchestrator-chain` (1000) and the default `para-id` for `container-chains` (also 1000 and now changed to 2000 as we have in moonwall).

Change default para id for templates

---

Cargo.lock
Cargo.toml
pallets/collator-assignment/Cargo.toml
pallets/collator-assignment/src/mock.rs
pallets/collator-assignment/src/tests.rs

In #385 I added a log for error cases that should never happen, but I didn't consider that they happen in tests. This results in `cargo test` currently printing this error multiple times:
```
ERROR pallet_collator_assignment::pallet: Error in collator assignment, will keep previous assignment. ZeroCollators
```
So this PR changes the default collator assignment in tests to avoid that error, and also includes a helper function to silence logs inside a test to avoid this problem in the future.

Avoid error log "ZeroCollators" when running cargo test

---

pnpm-lock.yaml
test/package.json

Uses published chopsticks instead of our fork, which should work now

use chopsticks 0.9.9.1

---

pallets/invulnerables/src/benchmarking.rs
pallets/invulnerables/src/lib.rs
pallets/invulnerables/src/tests.rs
pallets/invulnerables/src/weights.rs
typescript-api/src/dancebox/interfaces/augment-api-errors.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/augment-api-errors.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

Pass the check to `add_invulnerable` too, a check that only existed in `set_invulnerables`

check keys registered in add_invulnerable too

---

Cargo.lock
node/src/service.rs

Removes the second instance of spawn relay chain tasks, which seems to duplicate the import notifications for the container

remove start relay chain tasks duplicated

---

node/src/service.rs

Revert part of #409. Even though both approaches seem to work, in polkadot-sdk they have it outside the `if validator`.

start_relay_chain_tasks for full nodes as well

---

.github/workflows/release.yml
Cargo.lock
client/consensus/Cargo.toml
client/consensus/src/collators.rs
client/consensus/src/collators/basic.rs
client/consensus/src/consensus_orchestrator.rs
client/consensus/src/lib.rs
client/consensus/src/tests.rs
node/src/service.rs
pallets/registrar/rpc/runtime-api/src/lib.rs
runtime/dancebox/src/lib.rs
test/configs/zombieTanssiParathreads.json
test/moonwall.config.json
test/scripts/build-spec-parathreads.sh
test/scripts/sudoRegisterPara.ts
test/suites/parathreads/test_tanssi_parathreads.ts

Allows registered parathreads to produce blocks every n slots, where n is defined on chain.
This is ready to be tested, but it may need a refactor (`get_authorities_from_orchestrator` will probably need to be renamed)
How to test this:
* `pnpm moonwall test zombie_tanssi_parathreads`
This is a new zombienet test suite that is not being run in CI.
Or, to test manually:
* `pnpm moonwall run zombie_tanssi`
* Manually call Registrar.deregister for para id 2000
* `pnpm run sudo-register-para register --parathread --url ws://127.0.0.1:9948 --account //Alice --chain specs/template-container-2000.json`
* Manually call Registrar.setParathreadParams to adjust slotFrequency. Set min=max=5 to produce 1 block every 5 slots (60 seconds)
* Observe how parachain 2000 produces 1 block every 60 seconds.

Implement on demand block production

---

client/node-common/src/service.rs
container-chains/templates/frontier/node/src/service.rs
container-chains/templates/simple/node/src/service.rs
node/src/container_chain_monitor.rs
node/src/service.rs

We use a `NativeElseWasmExecutor` for all chains, but collators don't have the container chain's native runtime. So their executor was trying to use the native dancebox runtime as the container chain runtime, which fortunately resulted in a version mismatch and the wasm container chain runtime was always used.
This can be verified by starting zombienet with `export RUST_LOG=info,executor=trace`:
```
2024-02-13 18:33:48.286 TRACE tokio-runtime-worker executor: [Container-2000] Request for native execution failed native=dancebox-500 (dancebox-0.tx1.au1) chain=container-chain-template-500 (container-chain-template-0.tx1.au1)
```
As a bonus we now have two types of clients, `Arc<ContainerChainClient>` and `Arc<ParachainClient>`, and using one client in place of the other results in a compile …

Always use wasm executor in container collators

---

Cargo.lock
client/node-common/src/service.rs
container-chains/templates/frontier/node/src/cli.rs
container-chains/templates/frontier/node/src/command.rs
container-chains/templates/simple/node/src/cli.rs
container-chains/templates/simple/node/src/command.rs
node/src/cli.rs
node/src/command.rs
test/.gitignore
test/moonwall.config.json
test/scripts/compile-wasm.ts

`dev_tanssi` tests spawn a new `tanssi-node` process for each test. This node needs to compile the runtime wasm. That can take a long time. This pull request adds a flag to use a precompiled wasm, which means that now we only need to compile the wasm once.
Affects dev tests for tanssi, flashbox, and both templates.
Speeds up coverage job from 1h 20min to 1h 3m

Use precompiled wasm in dev tests

---

node/src/service.rs
test/configs/zombieTanssi.json
test/configs/zombieTanssiKeepDb.json
test/configs/zombieTanssiMetrics.json
test/configs/zombieTanssiParathreads.json
test/configs/zombieTanssiRotation.json
test/configs/zombieTanssiWarpSync.json
test/moonwall.config.json

Compile wasm once before starting all the zombienet nodes, instead of having each node compile it. This also makes rotations a bit faster, we will see if the block delay on rotation is reduced.
Also disable hardware benchmarks, they were enabled for collators and full nodes.

Use wasmtime-precompiled in zombienet tests

---

docker/container-chain-evm-template.Dockerfile
docker/container-chain-simple-template.Dockerfile
docker/tanssi.Dockerfile

Up to now we were only copying the main binaries (tanssi-node, container-chain-simple-template-node, etc) but not those based of skylake and znver3. This PR should fix this

copy all binaries to docker image

---

.github/workflows/publish-runtime-chevdor.yml
.github/workflows/publish-runtime.yml
docker/tanssi-srtool.Dockerfile

We have an issue where we need to use a specific srtool with certain components (rust-src) added, which are in this PR: https://github.com/paritytech/srtool/pull/81
I modified the publish-runtime job to have the possibility to build from a custom image (and not the official parity one) that I pushed with those changes.
Additioanlly, I also added another job that instead builds from the srtool CI action. We can use one or the other.

Build own srtool

---

test/moonwall.config.json
test/suites/keep-db/test_restart_keep_db.ts
test/suites/metrics/test_metrics_stop.ts
test/suites/para/test_tanssi_containers.ts
test/util/block.ts

Fixes a zombienet timeout caused by an extrinsic being included, reverted, and then included again in a later block.
For example, an extrinsic to deregister chain 2002:
* Deregister extrinsic included in block 29
* Test detects that and waits 2 sessions. In block 35 the chain should already be deregistered.
* Block 29 is reverted and the new block 29 does not include the extrinsic.
* Extrinsic is included again in block 32. The chain will be deregistered after 2 sessions, in block 40.
* In block 35, the script assumes that the chain must already be deregistered, while it's not, so the expect fails.
With the new changes, the script will wait until the extrinsic is finalized, meaning that it can be reverted anymore. A drawback is that it may wait 1 session more than needed. To fix this, the …

Wait for block to be finalized in signAndSendAndInclude

---

test/suites/para/test_tanssi_containers.ts

Waiting always 2 sessions can cause the test to fail, we need to wait 1 or 2 sessions depending on when the block that includes the extrinsic is finalized.

Fix registration zombienet test

---

pallets/registrar/src/lib.rs
pallets/registrar/src/mock.rs
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs

Not needed since we moved bootnodes to the data preservers pallet

Remove unused bootnodes config from pallet_registrar

---

container-chains/templates/frontier/node/src/service.rs
container-chains/templates/simple/node/src/service.rs
node/src/service.rs
pallets/initializer/src/mock.rs

This makes it faster to initialize a thread local variable, and if the inner type does not need to be dropped it also makes it faster to use. Shouldn't make any perf impact because this is only used in tests, but I didn't know about this feature so let's use it.
You can use this code to check if a type needs to be dropped, basically anything that uses the heap needs to be dropped:
```rust
use std::cell::RefCell;
fn main() {
dbg!(std::mem::needs_drop::<RefCell<u8>>()); // false
dbg!(std::mem::needs_drop::<RefCell<Option<(u32, Vec<u64>)>>>()); // true
}
```

Use const syntax in thread local macro

---

client/consensus/src/collators.rs
client/consensus/src/collators/basic.rs

Fixes the following panic present in the logs:
```
2024-03-13 16:56:06.023  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Container-2002] :raised_hands: Starting consensus session on top of parent 0x35551d29498f418c033e7faa19b69df6b8df0f7cffbdce9ca4076a95efd6ad29    
2024-03-13 16:56:06.024 ERROR tokio-runtime-worker runtime: [Container-2002] panicked at /home/builder/cargo/git/checkouts/moonkit-c6defa46a244ac75/9d006f9/pallets/async-backing/src/consensus_hook.rs:73:21:
Block invalid; Supplied slot number is not high enough
```
As related to https://github.com/paritytech/polkadot-sdk/pull/3308, it seems that with the current configuration of the basic collator, every para-block is attempted to be imported twice in the same slot, which is not the expected case with this …

Limit block production to one block per slot in basic collator

---

pallets/invulnerables/src/benchmarking.rs
pallets/invulnerables/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs
typescript-api/src/dancebox/interfaces/augment-api-errors.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/augment-api-errors.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

Currently, we are using `AccountId` and `CollatorId` interchangeably in the runtime. This works right now, since our `CollatorId` config type is set to  `AccountId` in runtime.
To be more idiomatic, we need to replace direct use of `AccountId` with `CollatorId` both in pallets and runtime. With `CollatorId` currently only type alias of `AccountId`. This make sure that both types are equivalent for now, but can be changed just by setting different type while building runtime.
This PR modifies `pallet_invulnerables` to use `CollatorId` instead of `AccountId` with some minor refactor involved.
In the runtime, we define type alias, and replace `AccountId` with `CollatorId` at required places.
This PR does not completely modifies runtime and all pallets to use `CollatorId`, only …

Use `CollatorId` instead of `AccountId` - Part 1 of N

---

.github/workflows/publish-docker.yml

While we create a tag with entire version i.e `vX.Y.Z` we are not pushing it to docker hub. This results in a scenario where while `vX` and `vX.Y` is updated on dockerhub, `vX.Y.Z` is not.
To fix this, we are pushing the `vX.Y.Z` image tag to DockerHub.

Push whole version as docker image tag to dockerhub

---

container-chains/templates/frontier/node/src/command.rs
container-chains/templates/simple/node/src/command.rs
node/src/command.rs

This PR renames `Parachain Collator Template` to `Tanssi Collator` for Tanssi node and `Container Chain Simple Node` for container chain template.

Rename Parachain Collator Template

---

pallets/collator-assignment/src/lib.rs
runtime/dancebox/src/lib.rs

We see some ugly logs when running the precompile-wasm script:
```
2024-03-14 13:43:07.955  INFO main dancebox_runtime: assembling new collators for new session 0 at #0    
2024-03-14 13:43:07.955  INFO main dancebox_runtime: assembling new collators for new session 1 at #0    
2024-03-14 13:43:07.955  INFO main pallet_collator_assignment::pallet: Collator assignment: keep old assigned. Session [0, 0, 0, 0], Seed: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]    
2024-03-14 13:43:08.494  INFO main sc_service::client::client: 🔨 Initializing Genesis block/state (state: 0x95bd…6339, header-hash: 0xedd5…ab9e)    
2024-03-14 13:43:08.509 TRACE main wasmtime-runtime: Computing wasm runtime hash [allow_missing_func_imports: false, code_hash: …
```

Move some logs to debug level

---

Cargo.lock
container-chains/templates/frontier/runtime/src/lib.rs
container-chains/templates/frontier/runtime/src/xcm_config.rs
container-chains/templates/simple/runtime/src/lib.rs
container-chains/templates/simple/runtime/src/xcm_config.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/src/xcm_config.rs
runtime/flashbox/src/lib.rs
typescript-api/src/dancebox/interfaces/augment-api-consts.ts
typescript-api/src/flashbox/interfaces/augment-api-consts.ts

This PR updates moonkit fork reference for tanssi. 
The first commit updates the commit reference in Cargo.lock. Second commit changes the runtimes to add the new types added in Config trait of some pallets.

Update Moonkit fork Reference

---

pallets/collator-assignment/src/assignment.rs
pallets/collator-assignment/src/lib.rs
pallets/collator-assignment/src/tests.rs
pallets/collator-assignment/src/tests/assign_full.rs

This will give more priority to collators with more stake.
Previously when the number of collators was much greater than the required, all collators were equally likely to be selected. Now, the first ones on the list are more likely to be selected.
Example with max_collators = 100, invulnerables = 5, min_orchestrator_collators = 2, max_orchestrator_collators = 5, and one container chain with 4 collators
* We take the 5 invulnerables, then 95 more collators from staking. These are the 95 with most stake.
* We assign 2 invulnerables to the orchestrator chain (prioritize_invulnerables)
* Now we need 3 collators more for orchestrator chain and 4 collators more for the container chain, 7 in total
Previously: we always shuffle the full list of collators, so we will take 7 collators randomly out …

Shuffle only top N collators to respect staking priority

---

pallets/collator-assignment/src/lib.rs
pallets/collator-assignment/src/mock.rs
pallets/configuration/src/lib.rs
primitives/traits/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/src/lib.rs
runtime/flashbox/tests/integration_test.rs

In `pallet_collator_assignment`, we use the pending config values to ensure that the current assignment always matches the current configuration state. So, if we change the value of `collators_per_container`, when the change is reflected in `configuration.config`, we should see that the number of collators per container in `pallet_collator_assignment` has also changed.
However we were not doing that with the value of `max_collators`, we were using the current value instead of the pending one. This PR fixes that.

Fix use of current max_collators instead of pending

---

container-chains/templates/frontier/runtime/src/lib.rs
container-chains/templates/simple/runtime/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/common/mod.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/src/lib.rs
runtime/flashbox/tests/common/mod.rs
runtime/flashbox/tests/integration_test.rs
test/suites/common-all/fee_balance_transfer/test_fee_balance_transfer.ts
test/suites/common-tanssi/fees/test_fee_burning.ts
test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
test/util/block.ts

Currently, we are using `ConstFeeMultiplier` for transaction payment, which mean that regardless of network congestion level, the transaction fee would be constant. This is not recommended since it can be DOS vector. 
Instead we need to use `SlowAdjustingFeeUpdate` which adjusts slowly, at the pace of long term tendencies, and uses tipping to give users the possibility of controlling waiting times at peak hours.

Use `SlowAdjustingFeeUpdate` instead of `ConstFeeMultiplier`

---

test/suites/smoke-test-dancebox/test-staking-consistency.ts

Currently, we are calculating delegation amount of candidate (referred to as delegator in this scenario) in the auto compounding pool by simply querying `AutoCompoundingSharesHeldStake` which is not updated against rewards earned by that delegator as the rewards simply increases value of each shares. 
This PR attempts to correct this by calculating delegation of delegator in auto compounding pool by:
```
(shares of delegator in auto pool * (total staked amount in auto pool / total supply of shares in auto pool);
```

Fix calculation of Auto compounding delegation of candidate

---

pallets/authority-mapping/src/lib.rs
pallets/configuration/src/lib.rs
pallets/data-preservers/src/lib.rs
pallets/inflation-rewards/src/lib.rs
pallets/invulnerables/src/lib.rs
pallets/pooled-staking/src/lib.rs
pallets/registrar/src/lib.rs
pallets/services-payment/src/lib.rs
pallets/xcm-core-buyer/src/lib.rs
typescript-api/src/dancebox/interfaces/augment-api-consts.ts
typescript-api/src/flashbox/interfaces/augment-api-consts.ts

Exposes pallet constants as constants so that they are accessible through polkadotJs

put all pallet constants as constant

---

test/scripts/download-polkadot.sh

If the polkadot-sdk binary fails to download, an html error page is saved instead of the binary. And the script tries to execute that html page as if it was a binary, resulting in funny errors like:
```
tmp/polkadot: line 1: !DOCTYPE: No such file or directory
```
Example: https://github.com/moondance-labs/tanssi/actions/runs/8615938633/job/23613523615?pr=489
This PR fixes that by removing any files that are not executables. Note that unfortunately it can still happen that we save an html file as `tmp/polkadot`, but with this PR it will be fixed by running the tests again.

Avoid executing html in download polkadot script

---

test/scripts/compile-wasm.ts

Do not generate raw chain spec when the argument is already a json chain spec.
Fixes this error that we see in CI:
```
Error: /bin/sh: 1: cannot create tmp/specs/parathreads-tanssi-1000.json.json: Directory nonexistent
```
The error breaks the wasm compilation step, but that's only an optimization, so tests will still pass without the precompiled wasm.
Caused by #469
I hope this doesn't revert the improvements from that PR...

Fix compile-wasm script

---

client/consensus/src/collators/lookahead.rs
node/src/container_chain_spawner.rs
node/src/service.rs
test/suites/para/test_tanssi_containers.ts

Fixes a bug where the collator process for the orchestrator chain will always keep running in the background, trying to produce blocks but not being able to because it is not eligible.
Consider a collator that goes from orchestrator to a container and then back, like 1000 -> 2001 -> 1000.
Before the PR, the collator process for 1000 was always running, being restarted during the transition to 2001 -> 1000.
After the PR, the collator process for 1000 is stopped during the first transition 1000 -> 2001, and then started again in the transition 2001 -> 1000.
Also includes a refactor on how the orchestrator collator is started, which shouldn't change the behavior but allows to remove some TODOs from unit tests, and a cleanup of a zombienet test that was always unreliable, which should reduce …

Stop orchestrator collator as soon as the node is unassigned

---

test/suites/para/test_tanssi_containers.ts

It can sometimes fail when we expect 4 different authors in 10 blocks, and we only see 3 authors. That's because the 4th author has just rotated from a container chain, and has not had enough time to propose a block for the orchestrator chain.
This test was broken by #492, I was too optimistic.

Fix zombienet test by undoing a change

---

node/src/container_chain_spawner.rs
test/suites/para/test_tanssi_containers.ts

Allows collators to keep running if there is any error when trying to start a container chain, or if the container chain has an essential tasks that stops unexpectedly. Note that any panics will still stop the node, regardless if they happen in the container chain task manager or in the orchestrator/relay. The only exception is panics that happen inside the runtime, those will never cause the node to stop.
Can be tested by reverting the commit 7af640409c82df81ab53b7baa0dda4232e2f0fcf and running `pnpm moonwall test zombie_tanssi`, the test will fail but inspecting the logs will show that the nodes did not crash.

Do not panic when container chain fails to start

---

test/suites/keep-db/test_restart_keep_db.ts
test/suites/metrics/test_metrics_stop.ts
test/suites/para/test_tanssi_containers.ts
test/suites/parathreads/test_tanssi_parathreads.ts
test/suites/rotation-para/test_rotation.ts
test/suites/warp-sync/test_warp_sync.ts

Increase some test timeouts.
With the change from 12 second block time to 6 second, some timeouts were not increased. Previously we waited for 3 tanssi block to assume finality, but finality depends on the relay chain, so we should have been waiting for 6 relay blocks. With this change we wait for 6 tanssi blocks, which should be the same.
Also I merged 2 batches of transactions into 1 batch, because using `signAndSendAndInclude` twice in the same test can make it time out depending on finality.

Improve more timeouts in zombienet tests

---

client/consensus/src/collators/lookahead.rs
node/src/container_chain_spawner.rs
pallets/invulnerables/src/benchmarking.rs
pallets/invulnerables/src/lib.rs
pallets/invulnerables/src/tests.rs
pallets/invulnerables/src/weights.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/tests/integration_test.rs
test/suites/dev-tanssi/session-keys/test_remove_session_key_staking.ts
test/suites/dev-tanssi/staking/test_staking_rewards_balanced.ts
test/suites/dev-tanssi/staking/test_staking_rewards_non_balanced.ts
test/suites/warp-sync/test_warp_sync.ts
test/util/invulnerables.ts
typescript-api/src/dancebox/interfaces/augment-api-tx.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/augment-api-tx.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

This PR solves 2 tickets:
MD326
- Removes set_invulnerables extrinsic
- Rewrites rust integration tests to use add_invulnerable instead of set_invulnerables
- Rewrites moonwall tests to use add_invulnerable instead of set_invulnerables
- Removes benchmark and weights related to set_invulnerables
MD325
- Changes the remove_invulnerable return type to charge the fees depending on the actual weight consumed in the execution
- Changes the benchmarking function to remove the last element, thus causing to have to read every element in the list and covering the worst-case scenario for the call

MD325/MD326 - invulnerables

---

pallets/stream-payment/src/lib.rs
pallets/stream-payment/src/mock.rs
pallets/stream-payment/src/tests.rs
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs
test/suites/common-tanssi/stream-payment/test_stream_payment.ts
typescript-api/src/dancebox/interfaces/augment-api-consts.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/augment-api-consts.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

Adds a balance hold (to the origin) when opening a `pallet_stream_payment` Stream to prevent possible storage bloat.

Stream payment deposit on opening a stream

---

Cargo.lock
node/src/service.rs
pallets/author-noting/Cargo.toml
pallets/author-noting/src/lib.rs
pallets/author-noting/src/mock.rs
pallets/author-noting/src/tests.rs
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/src/lib.rs
runtime/flashbox/tests/integration_test.rs

We want this slot number to be the tanssi slot number, not the container chain slot number. Doesn't need a migration because this is not yet deployed.

Store tanssi slot number in author noting pallet

---

test/suites/smoke-test-common/test-inflation-rewards.ts
test/suites/smoke-test-dancebox/test-randomness-consistency.ts

This PR fixes `S09C02` and `S08C03` typescript test by conditionally changing `sessionLength` and `inflationIncrement` depending upon whether runtime is > 500 or not.

Fix S09C02 and S08C03

---

runtime/flashbox/src/lib.rs

This enables a setting that was missing in flashbox, to allow collators to create multiple blocks after a delay in block production. Enabling this will improve the average block time. Dancebox has already enabled it, and we have tested it using zombienet.

Set AllowMultipleBlocksPerSlot = true in flashbox

---

runtime/dancebox/tests/common/mod.rs
runtime/dancebox/tests/common/xcm/core_buyer.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/src/lib.rs
runtime/flashbox/tests/common/mod.rs
runtime/flashbox/tests/integration_test.rs

Now we do on_finalize then on_initialize, so that after calling this function any extrinsics will be executed as if they were inside a block. Most of the tests are not affected by this change.
TODO (for future PRs): maybe try to extract run_block to a common crate `test_utils`.

Change run_block function in integration tests

---

container-chains/nodes/frontier/src/command.rs
container-chains/runtime-templates/frontier/src/xcm_config.rs
container-chains/runtime-templates/simple/src/xcm_config.rs
test/suites/common-xcm/xcm-token-reception/test_dmp_token_reception_teleport.ts
test/util/xcm.ts

Fixes the teleport policy as well as the command yield in the frontier template

forbid teleports and fix command in templates

---

pnpm-lock.yaml
typescript-api/package.json

Fixes error when generating typescript-api with pnpm v9 instead of v8.
```
sh: 1: rimraf: not found
 ELIFECYCLE  Command failed.
Error: Command failed: pnpm run build
```

Add rimraf to devDependencies

---

pallets/registrar/src/benchmarks.rs
pallets/registrar/src/lib.rs
runtime/common/src/migrations.rs
runtime/dancebox/tests/integration_test.rs
typescript-api/src/dancebox/interfaces/augment-api-query.ts
typescript-api/src/flashbox/interfaces/augment-api-query.ts

This allows an unlimited number of para ids to be waiting for verification, by using an unbounded `StorageMap<ParaId, ()>` instead of a bounded `StorageValue<Vec<ParaId>>`.
Breaking change, includes a migration.

Migrate PendingVerification in pallet_registrar from value to map

---

test/configs/zombieTanssiOneNode.json
test/moonwall.config.json
test/scripts/build-spec-one-node.sh
test/suites/one-node/test_tanssi_one_node.ts

Adds a new zombienet test suite with only 2 collators and 2 validators.
The goal is to check that registering an invalid runtime does not make the collator panic. This suite is not enabled in CI because even though it is very minimal, it still takes 4 minutes to run.

Add zombie_tanssi_one_node test suite

---

test/suites/smoke-test-common/test-inflation-rewards.ts

This PR removes an  `expect` which was checking `supplyAfter == supplyBefore + issuance`; since this cannot hold in scenarios where users burn their token or if protocol burn part of the payment it received.

Remove `expect` which was checking `supplyAfter == supplyBefore + issuance`

---

container-chains/nodes/frontier/src/client.rs
container-chains/nodes/frontier/src/service.rs
container-chains/nodes/simple/src/service.rs

We have seen a lot of people customizing the template runtime but not changing the spec name. This makes the full-nodes use the native compiled runtime and fail importing blocks.
I am not a big fan of doing it, but since it's the trend that comes from polkadot-sdk (see https://github.com/paritytech/polkadot-sdk/pull/4329) I guess we should start using only the wasm-executor

deprecate at least in container-chain nodes, native executor

---

Cargo.lock
Cargo.toml
client/services-payment/Cargo.toml
client/services-payment/src/lib.rs
node/Cargo.toml
node/src/rpc.rs
pallets/services-payment/rpc/runtime-api/Cargo.toml
pallets/services-payment/rpc/runtime-api/src/lib.rs
runtime/dancebox/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/flashbox/Cargo.toml
runtime/flashbox/src/lib.rs
test/suites/common-tanssi/services-payment/test_services_payment_rpc.ts

Adds a runtime API and node RPC methods for getting the block production and collator assignment cost for `ServicesPayment`

Services payment RPC

---

.github/workflows/release.yml

The Clippy workflow already runs with `runtime-benchmark` feature, making the `cargo check` in the CI workflow redundant.

Remove runtime-benchmark cargo check on CI

---

test/suites/smoke-test-common/test-inflation-rewards.ts
test/suites/smoke-test-dancebox/test-invulnerables-priority.ts
test/suites/smoke-test-dancebox/test-randomness-consistency.ts
test/util/block.ts

Fixes some smoke tests with respet to:
- left over session lenghts at 300.
- inflation-rewards sometimes failing because we are probably not using the same api to fetch author events and author digest log

Make some smoke tests more consistent

---

pallets/collator-assignment/src/lib.rs
pallets/collator-assignment/src/tests.rs

The implementation of collator priority in #471 has a bug that renders it useless: collators are being shuffled twice. This resulted in the priority being applied to a shuffled list of collators, so it was equivalent to having no priority.
This PR fixes that by removing one line: `collators.shuffle(&mut rng);`, and fixing all the tests that break because we changed the way we use the randomness. Also adds a new test `assign_collators_truncates_before_shuffling` to check that collator priority works as expected.

Fix: do not shuffle collators before applying priority

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/container_chain_spawner.rs

Improves the hack we use to wait for the database to close when restarting a container chain. Now instead of a `sleep(10)`, we wait until the database lock file is released (with a 60 second timeout).
Fix #554

Wait for lock file in container chain restart

---

test/configs/zombieTanssi.json
test/configs/zombieTanssiKeepDb.json
test/configs/zombieTanssiMetrics.json
test/configs/zombieTanssiOneNode.json
test/configs/zombieTanssiParathreads.json
test/configs/zombieTanssiRotation.json
test/configs/zombieTanssiWarpSync.json

Follow-up to #568 
The solution was just to use a full node as RPC, instead of using a tanssi collators as RPC. This works around the bug: https://github.com/paritytech/polkadot-sdk/issues/1202

Add tanssi full node to zombienet tests

---

Cargo.lock
Cargo.toml
container-chains/runtime-templates/frontier/Cargo.toml
container-chains/runtime-templates/frontier/src/lib.rs
container-chains/runtime-templates/frontier/src/migrations.rs
container-chains/runtime-templates/frontier/src/precompiles.rs
test/contracts/solidity/Proxy.sol
test/suites/dev-frontier-template/test-precompiles/test-precompile-proxy.ts
test/suites/dev-frontier-template/test-precompiles/test-precompile-smart-contract-call.ts
test/suites/dev-frontier-template/test-precompiles/test-precompile-xcm-utils.ts

Add Proxy precompiled smart contract from Moonkit to Frontier container chain at address `0x0000000000000000000000000000000000000805`

Proxy precompile in Frontier container chain runtime

---

Cargo.lock
Cargo.toml
container-chains/runtime-templates/frontier/Cargo.toml
container-chains/runtime-templates/frontier/src/migrations.rs
container-chains/runtime-templates/simple/Cargo.toml
container-chains/runtime-templates/simple/src/migrations.rs
pnpm-lock.yaml
runtime/common/Cargo.toml
runtime/dancebox/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/dancebox/tests/integration_test.rs
runtime/flashbox/Cargo.toml
runtime/flashbox/src/lib.rs
runtime/flashbox/tests/integration_test.rs

The `runtime-common` crate name conflicts with `polkadot-sdk:runtime-common`, therefore to make it easier to integrate more `polkadot-sdk` crates it should be renamed to `tanssi-runtime-common`

Rename runtime-common to tanssi-runtime-common

---

Cargo.lock
Cargo.toml
client/node-common/src/service.rs
container-chains/runtime-templates/frontier/Cargo.toml
container-chains/runtime-templates/frontier/src/lib.rs
container-chains/runtime-templates/simple/Cargo.toml
container-chains/runtime-templates/simple/src/lib.rs
runtime/dancebox/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/flashbox/Cargo.toml
runtime/flashbox/src/lib.rs
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/registry.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/registry.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

Allows to reclaim unused proof size. So if the benchmark says that an extrinsic will consume 1000 bytes because that's the worst case, but in reality it only consumes 10 bytes, the 990 bytes of difference will not count for the weight calculation and will be available for other extrinsics.
I followed this guide: https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/guides/enable_pov_reclaim/index.html
To test locally:
```
export RUST_LOG=runtime::storage_reclaim=trace
pnpm moonwall run zombie_tanssi_one_node
```
And in polkadot js, send any extrinsic, for example dataPreservers.createProfile. You will see this in node logs:
```
2024-06-12 13:08:54.022 TRACE tokio-runtime-worker runtime::storage_reclaim: [Orchestrator] Reclaiming storage weight. benchmarked: 3694, consumed: 38 …
```

Enable PoV reclaim in all runtimes

---

pallets/stream-payment/src/lib.rs
pallets/stream-payment/src/tests.rs
test/suites/common-tanssi/stream-payment/test_stream_payment.ts
test/suites/common-tanssi/stream-payment/test_stream_payment_rpc.ts
typescript-api/src/dancebox/interfaces/augment-api-errors.ts
typescript-api/src/dancebox/interfaces/lookup.ts
typescript-api/src/dancebox/interfaces/types-lookup.ts
typescript-api/src/flashbox/interfaces/augment-api-errors.ts
typescript-api/src/flashbox/interfaces/lookup.ts
typescript-api/src/flashbox/interfaces/types-lookup.ts

Prevents making a request with a mandatory change having a deadline in the past.
Also fix the `stream_payment_status` function to return `stalled = true` when deadline is reached.

Stream payment: Prevent making a request with a past deadline

---

.github/workflows/release.yml

Run the moonwall dev test suite for `starlight` in CI.

Add dev starlight moonwall test suite to CI

---

tools/benchmarking.sh

Before the bench script had two issues:
- when it reached benchamrks of `pallet_xcm_benchmarks`, the `TEMPLATE` was set to the one for XCM and it was not modified for the next benchmarks that run.
- the output file of  `pallet_xcm_benchmarks` by default was `pallet_xcm_benchmarks::generic.rs` and after this PR is `pallet_xcm_benchmarks_generic.rs`

fix bench script

---

Cargo.lock
Cargo.toml
client/manual-xcm/Cargo.toml
client/stream-payment/Cargo.toml
pallets/inflation-rewards/Cargo.toml
pallets/pooled-staking/Cargo.toml
primitives/author-noting-inherent/Cargo.toml
primitives/container-chain-genesis-data/Cargo.toml
runtime/relay-encoder/Cargo.toml
solo-chains/client/cli/Cargo.toml
solo-chains/node/tanssi-relay/Cargo.toml
solo-chains/runtime/starlight/constants/Cargo.toml

Remove some unused dependencies from our crates. Unused dependencies can be easily found by adding this to `Cargo.toml`:
```toml
[workspace.lints.rust]
unused-crate-dependencies = { level = "deny", priority = 1 }
```
But that has many false positives related to features and it suggests to remove some dependencies that are not unused, so it is not enabled in CI.

Remove unused dependencies

---

test/suites/parathreads/test_tanssi_parathreads.ts

Parathreads are still a bit unstable so this is expected

Increase error margin in parathead slot diff check

---

test/configs/zombieFlashbox.json
test/moonwall.config.json
test/scripts/build-spec-flashbox.sh
test/suites/para/test_tanssi_containers.ts

Identical to the dancebox suite zombie_tanssi, the only difference is in `test/scripts/build-spec-flashbox.sh`, which has `--chain flashbox-local` instead of dancebox-local.

Add zombie_flashbox moonwall suite, not enabled in CI

---

client/service-container-chain/src/service.rs
container-chains/runtime-templates/frontier/src/lib.rs
container-chains/runtime-templates/simple/src/lib.rs
node/src/service.rs
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs

Block authoring duration: 0.5s -> 2s
Frontier template gas limit: 15M -> 60M
Substrate block weight limit: 0.5e12 -> 2e12
https://github.com/paritytech/polkadot-sdk/pull/5195

Increase authoring duration to 2s and block weight limit x4

---

Cargo.lock
solo-chains/runtime/starlight/Cargo.toml
solo-chains/runtime/starlight/README.md
solo-chains/runtime/starlight/constants/src/lib.rs
solo-chains/runtime/starlight/src/genesis_config_presets.rs
solo-chains/runtime/starlight/src/lib.rs
solo-chains/runtime/starlight/src/tests/collator_assignment_tests.rs
solo-chains/runtime/starlight/src/tests/common/mod.rs
solo-chains/runtime/starlight/src/tests/mod.rs
solo-chains/runtime/starlight/src/tests/services_payment.rs

Adds `ServicePayment` pallet to Starlight runtime. This also enables service charging on collator assignment, free credits on registration and removal of assignment on insufficient credits.

ServicesPayment in Starlight runtime

---

test/moonwall.config.json
test/scripts/build-spec-single-container.sh
tools/github/generate-runtimes-body.ts

With the change from ParachainSystem to System for the authorized upgrade extrinsic, we are incorrectly generating the call hash for the extrinsic in the release. this pr fixes it

generate the authorize upgrade hash correctly in releases

---

test/moonwall.config.json

Since we are using flashbox as the tanssi chain now, this is a a bit slower than fast-runtime dancebox, but it provides better guarantees with respect to the images we publish in docker.
However we need to increase the timeout as we are seeing the jobs sometime taking a bit longer

increase timeout for container zombie upgrade tests

---

Cargo.lock
solo-chains/runtime/starlight/Cargo.toml

So we won't see `wasm:stripped` in zombienet logs if compiled with `--features force-debug`

Add force-debug feature to starlight

---

test/suites/parathreads/test_tanssi_parathreads.ts
test/util/xcm.ts

We had hardcoded addresses before, now I added a function that creates the address on the fly by asking the relay through a runtime-api

create function to calculate the relay prathread tank address in typescript

---

runtime/common/src/migrations.rs
runtime/dancebox/src/tests/integration_test.rs

This PR adds storage migration for addition of the field in tanssi's `HostConfiguration`. This was  introduced in https://github.com/moondance-labs/tanssi/pull/665

Add storage migration for parachain percentage

---

client/service-container-chain/src/spawner.rs
container-chains/nodes/simple/src/command.rs
node/src/service.rs
test/suites/warp-sync/test_warp_sync.ts

Remove the select_sync_mode function which apparently is no longer needed

Always use warp sync for container chains

---

test/suites/zombie-tanssi-relay/test-tanssi-relay.ts

Attempt to fix spurious failures that happen because container 2002 takes a bit too long to produce blocks. Example:
https://github.com/moondance-labs/tanssi/actions/runs/10937611643/job/30364262733#step:3:296

Increase timeout for zombie_tanssi_relay test

---

test/suites/one-node/test_tanssi_one_node.ts
test/suites/parathreads/test_tanssi_parathreads.ts
test/suites/rotation-para/test_rotation.ts
test/suites/zombie-tanssi-relay/test-tanssi-relay.ts

* setMaxParachainCoresPercentage to 99%. With the default value of 60% there are only 2 available cores for parachains, we need 3.
* setFullRotationPeriod(5) was already the default value, this is just to make it explicit.
* Remove some unneded awaits

Increase setMaxParachainCoresPercentage in zombie_tanssi_relay

---

.github/workflow-templates/zombienet-tests/action.yml
.github/workflows/e2e-test-bridge.yml
.github/workflows/release.yml
.github/workflows/run-zombienet-tests.yml
test/configs/zombieDancelightBridge.json

Adds a job to run the  e2e bridge tests when we merge to master or when we request workflow dispatch. 
You can check it out dispatching like:
`gh workflow run "Bridge e2e test"  --ref girazoki-add-bridge-e2e-testing -f run_id=11721156969
`

add workflow trigger for bridge e2e tests

---

pallets/external-validator-slashes/Cargo.toml

There was a bug in compilation of dancelight runtime with `runtime-benchmarks` in commit f8b66f38f93dc8fb2a1bbe9d2e44d14d21cbd1ca. 
In that commit we were accidentally injecting `std` feature into `runtime-benchmarks` feature in `external-validator-slashes` pallet. This PR removes it.

Prevent std feature injection in runtime-benchmarks feature

---

.github/workflows/release.yml

We are removing `SKIP_WASM_BUILD=1` environment variable from clippy check in CI because it skips building wasm binary. This can possibly result in some compilation issues in building wasm binary escapes CI.

remove SKIP_WASM_BUILD=1 environment variable

---

Cargo.lock
container-chains/nodes/frontier/Cargo.toml
container-chains/nodes/simple/Cargo.toml
container-chains/runtime-templates/frontier/src/lib.rs
container-chains/runtime-templates/simple/src/lib.rs
node/Cargo.toml
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs
solo-chains/node/tanssi-relay-service/Cargo.toml
solo-chains/node/tanssi-relay/Cargo.toml
solo-chains/runtime/dancelight/src/lib.rs

This PR bumps node version to `0.11.0` and runtime spec version to `1100`.

Bump node and runtime versions to 0.11.0 and 1100

---

client/service-container-chain/src/chain_spec.rs
client/service-container-chain/src/cli.rs

Not needed after new genesis builder code

Remove RawGenesisConfig

---

tools/benchmarking.sh

Fixes this error after running the benchmark:
Invalid input: Could not get absolute path for: $OUTPUT.
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Fix benchmarking script

---

test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts

Add test that validators inserted from Ethereum bridge are actually used by pallet session.
To be merged in #772, or rebase on master once #772 is merged.

Test operators appears in pallet session after bridging

---

test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts

This PR fixes the bridge e2e test by waiting for more sessions before comparing current validators and previous validators. 
Also, `earlyExit` is configured such that if the validators change before, the `waitSessions` function can return early.

Fix bridge e2e test

---

pallets/collator-assignment/src/benchmarking.rs
pallets/collator-assignment/src/lib.rs
pallets/collator-assignment/src/mock.rs
pallets/collator-assignment/src/tests.rs
pallets/services-payment/src/lib.rs
primitives/traits/src/lib.rs
runtime/dancebox/src/lib.rs
runtime/flashbox/src/lib.rs
solo-chains/runtime/dancelight/src/lib.rs

Combine `RemoveParaIdsWithNoCredit` and `CollatorAssignmentHook` in one trait with two methods.
Both method executes same logic. Only difference being `pre_assignment_*` method always rollback while `post_assignment_*` only rollback in case it errors out.
Naming and tests are still remaining. Just want to get some early feedback on overall design.

Combine `RemoveParaIdsWithNoCredit` and `CollatorAssignmentHook`

---

test/suites/smoke-test-dancelight/test-para-inclusion.ts

allowedAncestryLen means "how many blocks before the relay parent are allowed as well". So the max difference in block number is not `allowedAncestryLen`, but `allowedAncestryLen + 1`.

Fix off-by-one in inclusion smoke test

---

pallets/external-validator-slashes/src/lib.rs
pallets/external-validator-slashes/src/mock.rs
pallets/external-validator-slashes/src/tests.rs
solo-chains/runtime/dancelight/src/lib.rs

Simplified how slashes queue is constructed and processed, and trigger "page" processing once every block.

Simplify slashes queue processing

---

chains/orchestrator-relays/runtime/dancelight/src/weights/pallet_external_validator_slashes.rs
pallets/external-validator-slashes/src/benchmarking.rs
pallets/external-validator-slashes/src/lib.rs
pallets/external-validator-slashes/src/weights.rs

Change the function signature of `process_slashes_queue` to take the limit as argument, which helps benchmarking it. It also now returns the number of slashes processed to return the actually used weight.
Following suggestion in #793, I only read and write from storage once by moving the `for` loop inside the `mutate` call.

Benchmark slashes queue processing

---

chains/orchestrator-relays/runtime/dancelight/src/lib.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
pallets/external-validators-rewards/src/lib.rs
pallets/external-validators-rewards/src/mock.rs
pallets/external-validators-rewards/src/tests.rs
primitives/bridge/src/lib.rs
typescript-api/src/dancelight/interfaces/augment-api-events.ts
typescript-api/src/dancelight/interfaces/lookup.ts
typescript-api/src/dancelight/interfaces/registry.ts
typescript-api/src/dancelight/interfaces/types-lookup.ts

Adds more tests to `external-validators-rewards` pallet, more specifically covering (at both unit and integration level) that `OnEraEnd` hook behaves as expected, also checking that we are sending the correct information inside the `ReportRewards` command.
Note: a `RewardsMessageSent` event was added to the pallet for us to be able to track the information that is being sent.

Add more tests for `ExternalValidatorsRewards` pallet

---

.github/workflow-templates/typescript-tests-moonwall/action.yml

We have this line in a CI script:
```
echo "CPUS=$(lscpu | egrep '^CPU\(s\)' | grep -o '[0-9]*')" >> $GITHUB_ENV
```
After upgrading to Ubuntu 24.04, that fails. It seems the script expected to just get the number of CPUs, but with the new lscpu, it’s actually grepping two CPU(s) values:
```
CPU(s):                               32
CPU(s) scaling MHz:                   41%
```
so the command is returning two values (32, 41) and breaking the action.
The fix is just to grep for "CPU(s):" instead.

Fix lscpu regex for ubuntu 24.04

---

chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
pallets/external-validator-slashes/src/lib.rs
pallets/external-validator-slashes/src/tests.rs
primitives/bridge/src/lib.rs
typescript-api/src/dancelight/interfaces/lookup.ts
typescript-api/src/dancelight/interfaces/registry.ts
typescript-api/src/dancelight/interfaces/types-lookup.ts

This PR removes timestamp from the command and adds it into the slashes itself. This will enable each slash having different timestamp.

add timestamp to each slash

---

client/orchestrator-chain-rpc-interface/Cargo.toml
pallets/xcm-core-buyer/Cargo.toml

Some crates didn't have this set. In that case they use the default clippy config instead of ours, so we may miss some clippy warnings.

Add missing workspace lints = true

---

primitives/bridge/Cargo.toml
primitives/bridge/src/lib.rs
primitives/bridge/src/tests.rs

We were encoding the vector as a tuple and therefore lead to wrong encoding. This should fix it

fix eth encoding with respect to encoding slashes vector

---

chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/external_validators_tests.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
pallets/external-validator-slashes/src/lib.rs
pallets/external-validator-slashes/src/tests.rs
pallets/external-validators-rewards/src/lib.rs
pallets/external-validators-rewards/src/tests.rs
primitives/bridge/src/lib.rs
typescript-api/src/dancelight/interfaces/augment-api-events.ts
typescript-api/src/dancelight/interfaces/lookup.ts
typescript-api/src/dancelight/interfaces/types-lookup.ts

This PR adds `message_id` field to slash and reward messages which is populated by `ticket`'s `message_id`. To extract `message_id` from `ticket`, we added a `TicketInfo` trait.
Adding `message_id` will allow us to track the progress of particular message across the bridge.

Add message id to slash and reward message events

---

primitives/bridge/src/custom_do_process_message.rs
test/scripts/bridge/build-symbiotic-contracts.sh
test/scripts/bridge/set-env.sh
test/scripts/bridge/setup-relayer.sh
test/scripts/bridge/start-relayer.sh
test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts

This PR implements slash + rewards e2e tests version 1. 
The version 1 only checks if the message is indicated to be successfully processed by gateway. But, it does not verify if it is processed by trying to claim the reward and actually checking if slash is applied. This will be implemented by version 2.
Other changes:
- We increased `max_dispatch_gas` for `ReportRewards` and `ReportSlashes` to 1 million from 60k gas.
- We modified the test to check operator block production to check if operator is part of session validators.
- We now start secondary governance channel relayer for token registration.

Slash + rewards e2e test version 1

---

test/suites/smoke-test-dancelight/test-babe.ts

Updates to the new `PolkadotPrimitivesV8ValidatorAppSignature` type, the old `V7` doesn't exist anymore which makes the test to fail.

Fix type in BABE smoke test

---

test/scripts/bridge/set-env.sh

This PR adds `gsed` as a required dependency to run the e2e tests on macOS

Fix gsed dep in mac to run e2e tests

---

test/suites/smoke-test-dancelight/test-external-validators-rewards.ts

There was an error in a smoke test regarding how we check whether rewards expire. And this was because polkadotjs by default returns a default value there, so we cannot check this properly. Instead I changed it to retrieve all keys, and then check whether the key exists

fix smoke test regarding external validators rewards

---

Cargo.lock
chains/orchestrator-relays/runtime/dancelight/src/bridge_to_ethereum_config.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/ethereum_client.rs
test/scripts/bridge/assets/beacon-relay.json
test/scripts/bridge/assets/execution-relay.json
test/scripts/bridge/assets/genesis.json
test/scripts/bridge/set-env.sh
test/scripts/bridge/setup-relayer.sh
test/scripts/bridge/start-ethereum-node.sh
test/scripts/download-ethereum-client-test-files.sh
test/suites/dev-tanssi-relay/eth-client/test-eth-ciient-submit-update-same-period.ts
test/suites/dev-tanssi-relay/eth-client/test-eth-client-submit-update-cannot-be-done-without-injecting-new-committee.ts
test/suites/dev-tanssi-relay/ethereum-token-transfers/test_transfer_native_token.ts
typescript-api/src/dancelight/interfaces/lookup.ts
typescript-api/src/dancelight/interfaces/types-lookup.ts

This PR uses the latest relayer which includes compatibility with electra and also uses the latest commits in the ethereum client to support electra consensus updates: https://github.com/paritytech/polkadot-sdk/pull/7075

Update to electra consensus

---

.github/workflows/release.yml

Fixes check wasm size. Before we were not correctly passing the latest build id between steps, yielding the  job to always download the latest build (hence the typical no changes). Now we have changed this

fix check wasm size

---

chains/container-chains/runtime-templates/frontier/src/lib.rs
chains/orchestrator-paras/runtime/dancebox/src/tests/common/mod.rs
chains/orchestrator-paras/runtime/dancebox/src/tests/integration_test.rs
chains/orchestrator-paras/runtime/flashbox/src/tests/common/mod.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/common/mod.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/staking.rs

Currently we are using 18 decimales instead of 12 for the UNIT const.
This PR updates this to use 12 decimals like polkadot

Use 12 decimals for UNIT

---

test/polkadotReleaseMapping.json
test/scripts/download-polkadot.sh
test/scripts/downloadPolkadot.ts

Polkadot binaries can only be downloaded in linux x86_64, anything else needs manual compilation so the downloadPolkadot script is not useful.
Also update the checksum file because there has been a new minor polkadot release. When moonwall is asked to download the binaries for stable2412, it will check the most recent release. So if the checksum is for 1.16.2 but the latest binary is 1.16.3, it will download 1.16.3 and the checksum won't match, so it will be updated.
For the future, a better solution would be to save a mapping of branchName to binaryVersion, like "stable2412": "1.16.2"

Disable polkadot binary checksum check in unsupported archs

---

test/scripts/bridge/set-env.sh
test/suites/zombie_tanssi_relay_eth_bridge/test_zombie_tanssi_relay_eth_bridge.ts

Adds slashes e2e tests. I had to change a bit the deployment script, companion PR:
https://github.com/moondance-labs/tanssi-symbiotic/pull/64
Additionally I am pointing to the latest symbiotic contracts

test slashes in the e2e tests

---

Cargo.toml

RustRover highlights unused dependencies, so I tried to remove them all and everything compiles. Not sure what method they use, I believe we would need a third party command to automate this or add it to CI.
But I don't think it's worth the effort to automate this, as extra dependencies in the root Cargo.toml don't increase compile time because no package depends on them.

Remove unused dependencies from Cargo.toml

---

chains/orchestrator-relays/runtime/dancelight/src/lib.rs
chains/orchestrator-relays/runtime/dancelight/src/tests/inflation_rates.rs

Inflation rates are swapped between block and era. This PR fixes it and add tests ensuring they are used properly.

Fix swapped inflation rates in dancelight

---

pallets/external-validator-slashes/src/lib.rs

This PR fixes the returned weight value for the `on_offence` function inside `ExternalValidatorSlashes` pallet, by keeping track of the actual reads and writes that were performed during the function execution.

[ExternalValidatorSlashes] Proper weight calculation inside `on_offence`

---

test/package.json
test/scripts/unhashKey.ts
test/scripts/utils/network.ts

Given a raw storage key, try to find which pallet it belongs to, and which storage item
Usage:
```
pnpm unhash-key
pnpm unhash-key 0x94eadf0156a8ad5156507773d0471e4a49f6c9aa90c04982c05388649310f22f
pnpm unhash-key --url 'wss://dancelight.tanssi-api.network' 0x94eadf0156a8ad5156507773d0471e4a49f6c9aa90c04982c05388649310f22f
```
Sample output:
```
✅ Found matching prefix: pallet ParaScheduler 0x94eadf0156a8ad5156507773d0471e4a
✅ Found key in network Polkadot:
0x94eadf0156a8ad5156507773d0471e4a49f6c9aa90c04982c05388649310f22f: ParaScheduler ClaimQueue
```

unhash-key script

---

Cargo.lock
test/configs/dancebox.yml
test/configs/frontierContainer.yml
test/configs/stagenet-dancebox.yml
test/suites/rt-upgrade-chopsticks-frontier-template/test-upgrade-chain.ts
test/suites/rt-upgrade-chopsticks-orchestrator/test-upgrade-chain.ts
test/utils/block.ts
typescript-api/src/dancebox/interfaces/augment-api-consts.ts
typescript-api/src/dancelight/interfaces/augment-api-consts.ts

What this new test does (for non-flashbox chains) is:
- For "*light" chains, it creates a random query with para id 1. after the upgrade, it checks that the version of the query on-storage matches that advertised by the pallet
- For "*box" chains, it creates a query with the relay. THe reason is that mocking the connection to a parachain is much more difficult here. We also reset the query counter because some chains might have already a query to the relay, so we start fresh. The later verification is identical in both cases.
- For containers, same as for "box" chains
Unfortunately I did not get much help from the API for this
Companion: https://github.com/paritytech/polkadot-sdk/pull/8173

Add xcm versioning test to chopsticks upgrade

---

Cargo.lock
chains/orchestrator-relays/node/tanssi-relay/Cargo.toml

Fixes compile error after default-members Cargo.toml change:
error: none of the selected packages contains these features: force-debug

Explicitly add force-debug feature to tanssi-relay

---

.config/nextest.toml
.github/workflows/release.yml
chains/orchestrator-relays/runtime/dancelight/src/tests/slashes.rs
chains/orchestrator-relays/runtime/starlight/src/tests/slashes.rs

Previously we didn't pass it, but rust tests run very fast so the slowest one was 250 seconds. In starlight `EpochDurationInBlocks` is 6x that of dancelight, so that test should take 6x longer. However it takes ~20x longer. I don't know what is this extra factor, but anyway now with fast-runtime the slowest test takes less than 2 seconds.

Pass fast-runtime feature to nextest

---

.github/workflows/release.yml

Fixes error of incompatible dependency:
error: failed to compile `twiggy v0.7.0`, intermediate artifacts can be found at `/tmp/cargo-install7pqDs1`. To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
rustc 1.81.0 is not supported by the following package:
backtrace@0.3.75 requires rustc 1.82.0

Install locked twiggy version

---

chains/orchestrator-relays/runtime/dancelight/src/lib.rs
chains/orchestrator-relays/runtime/starlight/src/lib.rs

This PR increment runtime spec version to 1302 for *light chains.

Increment spec version to 1302 for light chains

---

chains/orchestrator-relays/client/cli/src/command.rs
chains/orchestrator-relays/node/tanssi-relay-service/src/chain_spec.rs

Add Tanssi chain spec configurations to allow spawning the node with `--chain=tanssi` option using the proper mainnet specification and bootnodes.

Allow to spawn the node with Tanssi specs

---

pnpm-lock.yaml
test/package.json

**Summary**:
Vitest [introduced](https://vitest.dev/blog/vitest-3-2.html#annotation-api) annotation API in 3.2.*, but we use:
"vitest": "3.1.3",
"@vitest/ui": "^3.1.3",
`vitest/ui` -> resolved to `3.2.3`, but vitest knows nothing about annotations, this is why it [fails](https://github.com/vitest-dev/vitest/blob/657e83f9faf869ee9bed98f606a4dd46d5bba978/packages/vitest/src/node/reporters/tap.ts#L87).
So we need to downgrade to 3.1.3 to be consistent with [moonwall](https://github.com/Moonsong-Labs/moonwall/blob/%40moonwall/cli%405.13.0/test/package.json) at version 5.13.0.

Fix for forEach issue

---

.rustfmt.toml
tools/iforgor/tanssi.toml

- Remove nightly setting `imports_granularity` which spams the terminal each time we run `cargo fmt`
- Cleanup iforgor config. A common issue I have is that runtime integration tests fail if `runtime-benchmarks` feature is enabled, so I'm splitting testing test for `runtime-benchmarks` (needed to test benchmarks) and `fast-runtime` (needed for runtime integration tests).

Cleanup rustfmt and iforgor config

---

.github/workflows/publish-binary-from-docker.yml
test/scripts/download-latest-rt-binaries.sh

For specific cases we might want the ability to publish a public release from a docker generated image. this new job does that by calling it like, e.g.,:
`gh workflow run .github/workflows/publish-binary-from-docker.yml -r=download-runtime-with-steroids -f binaries="tanssi-node tanssi-relay" -f tag_name=myrelease -f release_name=myrelease -f docker_tag=v0.13.0`
the binaries have to be provided with a white-space between them.
I had to modify the download-runtimes.sh to accept a couple of things:
- include-all-args to download all binaries for all architectures
- tag to be able to download from a specific docker tag
An example of this can be seen in draft releases

Ability to run publish-binary with a docker-uploaded image

---

scripts/cancel_all_but.sh

Sometimes we need to speed up the specific PR merge. 
Using this script, we can cancel all the other PR jobs except the specified one.

Script that cancels other PR-s besides the specific one

---

.github/workflows/release.yml

It was causing errors because of the http request to fetch the list of releases. But that was not needed so we can remove it.

Remove unused lastest_rt from set-tags job

---

.github/workflows/run-zombienet-tests.yml

Zombie upgrade tests work if we have the wasm runtimes in target/ dir. So modify the workflow to upload and download runtimes.
Example run:
https://github.com/moondance-labs/tanssi/actions/runs/16619186835/job/47019836720

Enable zombie upgrade tests in manual CI run

---

.github/workflows/release.yml

This PR adds `--force` flag to disable the error if the package already exists.

Fix for udeps if it is exists already.

---

test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_burns.ts
test/suites/common-tanssi/services-payment/test_service_payment_removes_tank_money_and_refunds.ts
test/suites/common-tanssi/services-payment/test_services_payment_block_credit_buying_free_combined.ts
test/suites/common-tanssi/services-payment/test_services_payment_collator_credit_buying_free_combined.ts
test/suites/common-tanssi/services-payment/test_services_payment_no_free_credits.ts
test/suites/dev-tanssi-relay/services-payment/test_services_payment_block_credits.ts
test/suites/dev-tanssi-relay/services-payment/test_services_payment_collator_credits.ts
test/suites/dev-tanssi-relay/services-payment/test_services_payment_cost_values.ts
test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-channel.ts
test/suites/dev-tanssi-relay/xcm/test-export-errors-if-no-token-registration.ts
test/suites/dev-tanssi-relay/xcm/test-export-expected--errors.ts
test/suites/dev-tanssi-relay/xcm/test-export-expected-errors.ts
test/suites/dev-tanssi-relay/xcm/test-export-message-faking-para-origin.ts
test/suites/dev-tanssi-relay/xcm/test-export-message-from-para.ts
test/suites/dev-tanssi-relay/xcm/test-export-without-sufficient-balance-sovereign.ts
test/suites/smoke-test-common-all/test-consistency-services-payment.ts
test/suites/smoke-test-common-all/test-services-payment-costs.ts
test/suites/smoke-test-common-solo/test-configuration-consistency.ts
test/utils/index.ts

this PRs changes cost constants for calls to the runtime-api itself. My plan is to have a test that tests the specific values, but then the rest should work with the runtime-api

change costs constants for rt api in dev tests

---

client/service-container-chain-spawner/src/spawner.rs
test/suites/zombie_tanssi_keep_db/test_zombie_tanssi_keep_db.ts
test/utils/dir-canary.ts
test/utils/index.ts

This PR fixes a bug where collator container chain folder are always deleted on startup. Only affects orchestrator collators (dancebox & flashbox), solochain collators are not affected (dancelight & starlight not affected).
Collators start assigned to the orchestrator chain by default. The db cleanup task runs on the first assignment, so it will remove all container chain folders. The fix is to skip the db_cleanup task in this first assignment, and wait for the real assignment with the container chain para ids.
Also fix the tests to handle this case.

Wait for first assignment for db_cleanup
